/* Uloge */
INSERT INTO uloga (naziv_uloga) VALUES ('admin');
INSERT INTO uloga (naziv_uloga) VALUES ('obican');
INSERT INTO uloga (naziv_uloga) VALUES ('serviser');

/* Statusi oglasa */
INSERT INTO status_oglasa (naziv_status) VALUES ('aktivan');
INSERT INTO status_oglasa (naziv_status) VALUES ('zavrsen');

/* Statusi ponuda */
INSERT INTO status_ponude (naziv_status) VALUES ('aktivna');
INSERT INTO status_ponude (naziv_status) VALUES ('prihvacena');
INSERT INTO status_ponude (naziv_status) VALUES ('odbijena');
INSERT INTO status_ponude (naziv_status) VALUES ('obrisana');

/* Glavne kategorije */
INSERT INTO kategorija_kvara (naziv_kategorija_kvara, sif_roditelj) VALUES ('Svi oglasi', NULL);
INSERT INTO kategorija_kvara (naziv_kategorija_kvara, sif_roditelj) VALUES ('Servis računala', 1);
INSERT INTO kategorija_kvara (naziv_kategorija_kvara, sif_roditelj) VALUES ('Servis mobitela i tableta', 1);
INSERT INTO kategorija_kvara (naziv_kategorija_kvara, sif_roditelj) VALUES ('Servis konzola', 1);
INSERT INTO kategorija_kvara (naziv_kategorija_kvara, sif_roditelj) VALUES ('Bijela tehnika', 1);
INSERT INTO kategorija_kvara (naziv_kategorija_kvara, sif_roditelj) VALUES ('Ostali uređaji', 1);

/* Računala - glavne kategorije */
INSERT INTO kategorija_kvara (naziv_kategorija_kvara, sif_roditelj) VALUES ('Popravak računala', 2);
INSERT INTO kategorija_kvara (naziv_kategorija_kvara, sif_roditelj) VALUES ('Održavanje računala', 2);
INSERT INTO kategorija_kvara (naziv_kategorija_kvara, sif_roditelj) VALUES ('Instalacije programa', 2);
INSERT INTO kategorija_kvara (naziv_kategorija_kvara, sif_roditelj) VALUES ('Instalacija operativnog sistema', 2);
INSERT INTO kategorija_kvara (naziv_kategorija_kvara, sif_roditelj) VALUES ('Čišćenje virusa', 2);
INSERT INTO kategorija_kvara (naziv_kategorija_kvara, sif_roditelj) VALUES ('Uklanjanje prašine i zamjena termalne paste', 2);
INSERT INTO kategorija_kvara (naziv_kategorija_kvara, sif_roditelj) VALUES ('Zamjena baterije za laptop', 2);
INSERT INTO kategorija_kvara (naziv_kategorija_kvara, sif_roditelj) VALUES ('Popravak konektora', 2);
INSERT INTO kategorija_kvara (naziv_kategorija_kvara, sif_roditelj) VALUES ('Ostalo', 2);

/* Mobiteli */
INSERT INTO kategorija_kvara (naziv_kategorija_kvara, sif_roditelj) VALUES ('Zamjena stakla', 3);
INSERT INTO kategorija_kvara (naziv_kategorija_kvara, sif_roditelj) VALUES ('Zamjena ekrana', 3);
INSERT INTO kategorija_kvara (naziv_kategorija_kvara, sif_roditelj) VALUES ('Zamjena baterije', 3);
INSERT INTO kategorija_kvara (naziv_kategorija_kvara, sif_roditelj) VALUES ('Zamjena kamere', 3);
INSERT INTO kategorija_kvara (naziv_kategorija_kvara, sif_roditelj) VALUES ('Zamjena poklopca', 3);
INSERT INTO kategorija_kvara (naziv_kategorija_kvara, sif_roditelj) VALUES ('Zamjena konektora punjenja', 3);
INSERT INTO kategorija_kvara (naziv_kategorija_kvara, sif_roditelj) VALUES ('Zamjena zvučnika i senzora', 3);
INSERT INTO kategorija_kvara (naziv_kategorija_kvara, sif_roditelj) VALUES ('Zamjena matične ploče', 3);
INSERT INTO kategorija_kvara (naziv_kategorija_kvara, sif_roditelj) VALUES ('Popravak softwera', 3);
INSERT INTO kategorija_kvara (naziv_kategorija_kvara, sif_roditelj) VALUES ('Otključavanje', 3);
INSERT INTO kategorija_kvara (naziv_kategorija_kvara, sif_roditelj) VALUES ('Ostalo', 3);

/* Konzole  */
INSERT INTO kategorija_kvara (naziv_kategorija_kvara, sif_roditelj) VALUES ('Playstation 1', 4);
INSERT INTO kategorija_kvara (naziv_kategorija_kvara, sif_roditelj) VALUES ('Playstation 2', 4);
INSERT INTO kategorija_kvara (naziv_kategorija_kvara, sif_roditelj) VALUES ('Playstation 3', 4);
INSERT INTO kategorija_kvara (naziv_kategorija_kvara, sif_roditelj) VALUES ('Playstation 4', 4);
INSERT INTO kategorija_kvara (naziv_kategorija_kvara, sif_roditelj) VALUES ('Playstation 5', 4);
INSERT INTO kategorija_kvara (naziv_kategorija_kvara, sif_roditelj) VALUES ('Playstation Portable', 4);
INSERT INTO kategorija_kvara (naziv_kategorija_kvara, sif_roditelj) VALUES ('Playstation Vita', 4);
INSERT INTO kategorija_kvara (naziv_kategorija_kvara, sif_roditelj) VALUES ('Xbox 360', 4);
INSERT INTO kategorija_kvara (naziv_kategorija_kvara, sif_roditelj) VALUES ('Xbox One', 4);
INSERT INTO kategorija_kvara (naziv_kategorija_kvara, sif_roditelj) VALUES ('Nintendo Wii', 4);
INSERT INTO kategorija_kvara (naziv_kategorija_kvara, sif_roditelj) VALUES ('Nintendo Wii U', 4);
INSERT INTO kategorija_kvara (naziv_kategorija_kvara, sif_roditelj) VALUES ('Nintendo 3DS', 4);
INSERT INTO kategorija_kvara (naziv_kategorija_kvara, sif_roditelj) VALUES ('Nintendo Switch', 4);

/* Bijela tehnika */
INSERT INTO kategorija_kvara (naziv_kategorija_kvara, sif_roditelj) VALUES ('Perilice posuđa', 5);
INSERT INTO kategorija_kvara (naziv_kategorija_kvara, sif_roditelj) VALUES ('Perilice rublja', 5);
INSERT INTO kategorija_kvara (naziv_kategorija_kvara, sif_roditelj) VALUES ('Sučilice rublja', 5);
INSERT INTO kategorija_kvara (naziv_kategorija_kvara, sif_roditelj) VALUES ('Hladnjaci', 5);
INSERT INTO kategorija_kvara (naziv_kategorija_kvara, sif_roditelj) VALUES ('Pećnice', 5);
INSERT INTO kategorija_kvara (naziv_kategorija_kvara, sif_roditelj) VALUES ('Štednjaci', 5);
INSERT INTO kategorija_kvara (naziv_kategorija_kvara, sif_roditelj) VALUES ('Nape', 5);
INSERT INTO kategorija_kvara (naziv_kategorija_kvara, sif_roditelj) VALUES ('Zamrzivači', 5);
INSERT INTO kategorija_kvara (naziv_kategorija_kvara, sif_roditelj) VALUES ('Bojleri', 5);

/* Slike koriničkih profila */
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-cottonbro-4067768', 'aznrtldugdfhxf10m2md', 'https://res.cloudinary.com/eservis/image/upload/v1620167835/aznrtldugdfhxf10m2md.jpg', NULL);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-luis-quintero-1759530', 'xcbdltsn2kotq1bjj2ao', 'https://res.cloudinary.com/eservis/image/upload/v1620167842/xcbdltsn2kotq1bjj2ao.jpg', NULL);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-pixabay-415829', 'calrx4mhyi5zzuj93ff3', 'https://res.cloudinary.com/eservis/image/upload/v1620167894/calrx4mhyi5zzuj93ff3.jpg', NULL);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-andrea-piacquadio-943084', 'ehjrfzopwoxylelfoz6i', 'https://res.cloudinary.com/eservis/image/upload/v1620167900/ehjrfzopwoxylelfoz6i.jpg', NULL);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-chloe-1043471', 'wqywccfi29fem2ndlcb4', 'https://res.cloudinary.com/eservis/image/upload/v1620167907/wqywccfi29fem2ndlcb4.jpg', NULL);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-giftpunditscom-1310522', 'kwbeqjf92d5hb9zochvr', 'https://res.cloudinary.com/eservis/image/upload/v1620167913/kwbeqjf92d5hb9zochvr.jpg', NULL);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-suliman-sallehi-1704488', 'z8lnj4evdsydata4041t', 'https://res.cloudinary.com/eservis/image/upload/v1620167918/z8lnj4evdsydata4041t.jpg', NULL);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-mohamed-abdelghaffar-771742', 'lix8kwcningchcasj96h', 'https://res.cloudinary.com/eservis/image/upload/v1620167923/lix8kwcningchcasj96h.jpg', NULL);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-pixabay-220453', 'w0izyetennwg1pnay0tp', 'https://res.cloudinary.com/eservis/image/upload/v1620167930/w0izyetennwg1pnay0tp.jpg', NULL);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-cottonbro-4067768', 'l0mqlqzynedud2lono6b', 'https://res.cloudinary.com/eservis/image/upload/v1620167952/l0mqlqzynedud2lono6b.jpg', NULL);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-luis-quintero-1759530', 'puohfxldj0e4nwjyez4g', 'https://res.cloudinary.com/eservis/image/upload/v1620167959/puohfxldj0e4nwjyez4g.jpg', NULL);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-pixabay-415829', 'nsdnxkzxnagraswpzupj', 'https://res.cloudinary.com/eservis/image/upload/v1620167966/nsdnxkzxnagraswpzupj.jpg', NULL);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-andrea-piacquadio-943084', 'wxupnouwl30ytltcnwfm', 'https://res.cloudinary.com/eservis/image/upload/v1620167972/wxupnouwl30ytltcnwfm.jpg', NULL);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-chloe-1043471', 'vdv8syz7ep7p4bnpzpyv', 'https://res.cloudinary.com/eservis/image/upload/v1620167978/vdv8syz7ep7p4bnpzpyv.jpg', NULL);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-giftpunditscom-1310522', 'hwnya3hacenwfl8mlvk8', 'https://res.cloudinary.com/eservis/image/upload/v1620167985/hwnya3hacenwfl8mlvk8.jpg', NULL);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-suliman-sallehi-1704488', 'jkpa7kkhn2fmzgwprszr', 'https://res.cloudinary.com/eservis/image/upload/v1620167990/jkpa7kkhn2fmzgwprszr.jpg', NULL);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-mohamed-abdelghaffar-771742', 'zqskbrqmbfk1hmcgznvh', 'https://res.cloudinary.com/eservis/image/upload/v1620167995/zqskbrqmbfk1hmcgznvh.jpg', NULL);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-pixabay-220453', 'zzxdeg0zblyjxowf4zgg', 'https://res.cloudinary.com/eservis/image/upload/v1620168003/zzxdeg0zblyjxowf4zgg.jpg', NULL);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-cottonbro-4067768', 'lq6sxosjzkqfzh1ulsnm', 'https://res.cloudinary.com/eservis/image/upload/v1620168011/lq6sxosjzkqfzh1ulsnm.jpg', NULL);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-luis-quintero-1759530', 'pbsuqzak04tn0a7icgtd', 'https://res.cloudinary.com/eservis/image/upload/v1620168018/pbsuqzak04tn0a7icgtd.jpg', NULL);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-pixabay-415829', 'tcexcgremmdwnysbxiyx', 'https://res.cloudinary.com/eservis/image/upload/v1620168025/tcexcgremmdwnysbxiyx.jpg', NULL);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-andrea-piacquadio-943084', 'ogsysraixx66sw7oszcb', 'https://res.cloudinary.com/eservis/image/upload/v1620168032/ogsysraixx66sw7oszcb.jpg', NULL);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-chloe-1043471', 'fqgmjtggjllzvosoeskv', 'https://res.cloudinary.com/eservis/image/upload/v1620168043/fqgmjtggjllzvosoeskv.jpg', NULL);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-giftpunditscom-1310522', 'ltnjsh6tdeezi7gpode4', 'https://res.cloudinary.com/eservis/image/upload/v1620168050/ltnjsh6tdeezi7gpode4.jpg', NULL);

/* Slike servisa */
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-garrett-morrow-1337247', 'lba0et08am38479kfbjg', 'https://res.cloudinary.com/eservis/image/upload/v1620168470/lba0et08am38479kfbjg.jpg', NULL);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-lisa-4511372', 'jld92sy3xfthwy2k6xhd', 'https://res.cloudinary.com/eservis/image/upload/v1620168479/jld92sy3xfthwy2k6xhd.jpg', NULL);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-dmitry-demidov-3784566', 'ky63uaffxgolwns7aqd6', 'https://res.cloudinary.com/eservis/image/upload/v1620168488/ky63uaffxgolwns7aqd6.jpg', NULL);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-skitterphoto-1388947', 'aius8jszxj63ylj8hyfi', 'https://res.cloudinary.com/eservis/image/upload/v1620168493/aius8jszxj63ylj8hyfi.jpg', NULL);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-tyler-lastovich-719399', 'wveacjivasrbs5ajvgqs', 'https://res.cloudinary.com/eservis/image/upload/v1620168499/wveacjivasrbs5ajvgqs.jpg', NULL);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-athena-2582931', 'kbl9jzf7q8qoinbhr47r', 'https://res.cloudinary.com/eservis/image/upload/v1620168508/kbl9jzf7q8qoinbhr47r.jpg', NULL);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-pixabay-257886', 'qngs1cjss0oclcotetzt', 'https://res.cloudinary.com/eservis/image/upload/v1620168514/qngs1cjss0oclcotetzt.jpg', NULL);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-josh-sorenson-1054397', 'gqwivfpddxt1k5w3bbrx', 'https://res.cloudinary.com/eservis/image/upload/v1620168521/gqwivfpddxt1k5w3bbrx.jpg', NULL);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-pixabay-257736', 'pghq2o7so7l8xun8qeaj', 'https://res.cloudinary.com/eservis/image/upload/v1620168526/pghq2o7so7l8xun8qeaj.jpg', NULL);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-garrett-morrow-1337247', 'wkfnsm2zyiaz6wbhyv01', 'https://res.cloudinary.com/eservis/image/upload/v1620168532/wkfnsm2zyiaz6wbhyv01.jpg', NULL);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-lisa-4511372', 'x3xqvyh9vkhvvbz5n4ey', 'https://res.cloudinary.com/eservis/image/upload/v1620168541/x3xqvyh9vkhvvbz5n4ey.jpg', NULL);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-dmitry-demidov-3784566', 'd4dxfrislk1upf03deaj', 'https://res.cloudinary.com/eservis/image/upload/v1620168547/d4dxfrislk1upf03deaj.jpg', NULL);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-skitterphoto-1388947', 'f63dmak07ucc0nbbkyus', 'https://res.cloudinary.com/eservis/image/upload/v1620168552/f63dmak07ucc0nbbkyus.jpg', NULL);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-tyler-lastovich-719399', 'gcquixq6awkhg7bcnqbg', 'https://res.cloudinary.com/eservis/image/upload/v1620168557/gcquixq6awkhg7bcnqbg.jpg', NULL);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-athena-2582931', 'gh66f3duxi27tujx7ymb', 'https://res.cloudinary.com/eservis/image/upload/v1620168566/gh66f3duxi27tujx7ymb.jpg', NULL);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-pixabay-257886', 'cq5k3wzvzebinhr68ayj', 'https://res.cloudinary.com/eservis/image/upload/v1620168571/cq5k3wzvzebinhr68ayj.jpg', NULL);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-josh-sorenson-1054397', 'wezixahhciplji0cpwjq', 'https://res.cloudinary.com/eservis/image/upload/v1620168579/wezixahhciplji0cpwjq.jpg', NULL);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-pixabay-257736', 'xft2o7pdo0ykkx4mopj9', 'https://res.cloudinary.com/eservis/image/upload/v1620168585/xft2o7pdo0ykkx4mopj9.jpg', NULL);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-garrett-morrow-1337247', 'arbmqyvv1moqwtckvuhr', 'https://res.cloudinary.com/eservis/image/upload/v1620168590/arbmqyvv1moqwtckvuhr.jpg', NULL);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-dmitry-demidov-3784566', 'qfljirvtovlzavfwh6lw', 'https://res.cloudinary.com/eservis/image/upload/v1620168596/qfljirvtovlzavfwh6lw.jpg', NULL);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-tyler-lastovich-719399', 'ppunyrr7burbqx4o7orf', 'https://res.cloudinary.com/eservis/image/upload/v1620168602/ppunyrr7burbqx4o7orf.jpg', NULL);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-athena-2582931', 'n8r5aabgikhcw6orpzyd', 'https://res.cloudinary.com/eservis/image/upload/v1620168611/n8r5aabgikhcw6orpzyd.jpg', NULL);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-pixabay-257886', 's4jacs4d0u48s2ymtrus', 'https://res.cloudinary.com/eservis/image/upload/v1620168617/s4jacs4d0u48s2ymtrus.jpg', NULL);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-josh-sorenson-1054397', 'ujkzuozquo9uq6ls24v6', 'https://res.cloudinary.com/eservis/image/upload/v1620168624/ujkzuozquo9uq6ls24v6.jpg', NULL);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-pixabay-257736', 'e74yig41wumecmzktrzh', 'https://res.cloudinary.com/eservis/image/upload/v1620168630/e74yig41wumecmzktrzh.jpg', NULL);

/* Računi običnih korisnika */
INSERT INTO korisnik (email, lozinka, sif_uloga, verzija_tokena, trenutak_stvaranja, trenutak_promjene, sif_slika_profila) VALUES ('user1@gmail.com', '$2a$10$KPj2gHFAd5cpbX1payzmsuKgkFVG/DusXMgiTnldEauaThDoVLNIa', 2, 0, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 1);
INSERT INTO korisnik (email, lozinka, sif_uloga, verzija_tokena, trenutak_stvaranja, trenutak_promjene, sif_slika_profila) VALUES ('user2@gmail.com', '$2a$10$KPj2gHFAd5cpbX1payzmsuKgkFVG/DusXMgiTnldEauaThDoVLNIa', 2, 0, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 2);
INSERT INTO korisnik (email, lozinka, sif_uloga, verzija_tokena, trenutak_stvaranja, trenutak_promjene, sif_slika_profila) VALUES ('user3@gmail.com', '$2a$10$KPj2gHFAd5cpbX1payzmsuKgkFVG/DusXMgiTnldEauaThDoVLNIa', 2, 0, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 3);
INSERT INTO korisnik (email, lozinka, sif_uloga, verzija_tokena, trenutak_stvaranja, trenutak_promjene, sif_slika_profila) VALUES ('user4@gmail.com', '$2a$10$KPj2gHFAd5cpbX1payzmsuKgkFVG/DusXMgiTnldEauaThDoVLNIa', 2, 0, NOW()::TIMESTAMP, NOW()::TIMESTAMP, NULL);
INSERT INTO korisnik (email, lozinka, sif_uloga, verzija_tokena, trenutak_stvaranja, trenutak_promjene, sif_slika_profila) VALUES ('user5@gmail.com', '$2a$10$KPj2gHFAd5cpbX1payzmsuKgkFVG/DusXMgiTnldEauaThDoVLNIa', 2, 0, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 5);
INSERT INTO korisnik (email, lozinka, sif_uloga, verzija_tokena, trenutak_stvaranja, trenutak_promjene, sif_slika_profila) VALUES ('user6@gmail.com', '$2a$10$KPj2gHFAd5cpbX1payzmsuKgkFVG/DusXMgiTnldEauaThDoVLNIa', 2, 0, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 6);
INSERT INTO korisnik (email, lozinka, sif_uloga, verzija_tokena, trenutak_stvaranja, trenutak_promjene, sif_slika_profila) VALUES ('user7@gmail.com', '$2a$10$KPj2gHFAd5cpbX1payzmsuKgkFVG/DusXMgiTnldEauaThDoVLNIa', 2, 0, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 7);
INSERT INTO korisnik (email, lozinka, sif_uloga, verzija_tokena, trenutak_stvaranja, trenutak_promjene, sif_slika_profila) VALUES ('user8@gmail.com', '$2a$10$KPj2gHFAd5cpbX1payzmsuKgkFVG/DusXMgiTnldEauaThDoVLNIa', 2, 0, NOW()::TIMESTAMP, NOW()::TIMESTAMP, NULL);
INSERT INTO korisnik (email, lozinka, sif_uloga, verzija_tokena, trenutak_stvaranja, trenutak_promjene, sif_slika_profila) VALUES ('user9@gmail.com', '$2a$10$KPj2gHFAd5cpbX1payzmsuKgkFVG/DusXMgiTnldEauaThDoVLNIa', 2, 0, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 9);
INSERT INTO korisnik (email, lozinka, sif_uloga, verzija_tokena, trenutak_stvaranja, trenutak_promjene, sif_slika_profila) VALUES ('user10@gmail.com', '$2a$10$KPj2gHFAd5cpbX1payzmsuKgkFVG/DusXMgiTnldEauaThDoVLNIa', 2, 0, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 4);
INSERT INTO korisnik (email, lozinka, sif_uloga, verzija_tokena, trenutak_stvaranja, trenutak_promjene, sif_slika_profila) VALUES ('user11@gmail.com', '$2a$10$KPj2gHFAd5cpbX1payzmsuKgkFVG/DusXMgiTnldEauaThDoVLNIa', 2, 0, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 8);
INSERT INTO korisnik (email, lozinka, sif_uloga, verzija_tokena, trenutak_stvaranja, trenutak_promjene, sif_slika_profila) VALUES ('user12@gmail.com', '$2a$10$KPj2gHFAd5cpbX1payzmsuKgkFVG/DusXMgiTnldEauaThDoVLNIa', 2, 0, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 24);
INSERT INTO korisnik (email, lozinka, sif_uloga, verzija_tokena, trenutak_stvaranja, trenutak_promjene, sif_slika_profila) VALUES ('user13@gmail.com', '$2a$10$KPj2gHFAd5cpbX1payzmsuKgkFVG/DusXMgiTnldEauaThDoVLNIa', 2, 0, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 10);
INSERT INTO korisnik (email, lozinka, sif_uloga, verzija_tokena, trenutak_stvaranja, trenutak_promjene, sif_slika_profila) VALUES ('user14@gmail.com', '$2a$10$KPj2gHFAd5cpbX1payzmsuKgkFVG/DusXMgiTnldEauaThDoVLNIa', 2, 0, NOW()::TIMESTAMP, NOW()::TIMESTAMP, NULL);
INSERT INTO korisnik (email, lozinka, sif_uloga, verzija_tokena, trenutak_stvaranja, trenutak_promjene, sif_slika_profila) VALUES ('user15@gmail.com', '$2a$10$KPj2gHFAd5cpbX1payzmsuKgkFVG/DusXMgiTnldEauaThDoVLNIa', 2, 0, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 11);
INSERT INTO korisnik (email, lozinka, sif_uloga, verzija_tokena, trenutak_stvaranja, trenutak_promjene, sif_slika_profila) VALUES ('user16@gmail.com', '$2a$10$KPj2gHFAd5cpbX1payzmsuKgkFVG/DusXMgiTnldEauaThDoVLNIa', 2, 0, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 12);
INSERT INTO korisnik (email, lozinka, sif_uloga, verzija_tokena, trenutak_stvaranja, trenutak_promjene, sif_slika_profila) VALUES ('user17@gmail.com', '$2a$10$KPj2gHFAd5cpbX1payzmsuKgkFVG/DusXMgiTnldEauaThDoVLNIa', 2, 0, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 13);
INSERT INTO korisnik (email, lozinka, sif_uloga, verzija_tokena, trenutak_stvaranja, trenutak_promjene, sif_slika_profila) VALUES ('user18@gmail.com', '$2a$10$KPj2gHFAd5cpbX1payzmsuKgkFVG/DusXMgiTnldEauaThDoVLNIa', 2, 0, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 23);
INSERT INTO korisnik (email, lozinka, sif_uloga, verzija_tokena, trenutak_stvaranja, trenutak_promjene, sif_slika_profila) VALUES ('user19@gmail.com', '$2a$10$KPj2gHFAd5cpbX1payzmsuKgkFVG/DusXMgiTnldEauaThDoVLNIa', 2, 0, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 14);
INSERT INTO korisnik (email, lozinka, sif_uloga, verzija_tokena, trenutak_stvaranja, trenutak_promjene, sif_slika_profila) VALUES ('user20@gmail.com', '$2a$10$KPj2gHFAd5cpbX1payzmsuKgkFVG/DusXMgiTnldEauaThDoVLNIa', 2, 0, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 15);
INSERT INTO korisnik (email, lozinka, sif_uloga, verzija_tokena, trenutak_stvaranja, trenutak_promjene, sif_slika_profila) VALUES ('user21@gmail.com', '$2a$10$KPj2gHFAd5cpbX1payzmsuKgkFVG/DusXMgiTnldEauaThDoVLNIa', 2, 0, NOW()::TIMESTAMP, NOW()::TIMESTAMP, NULL);
INSERT INTO korisnik (email, lozinka, sif_uloga, verzija_tokena, trenutak_stvaranja, trenutak_promjene, sif_slika_profila) VALUES ('user22@gmail.com', '$2a$10$KPj2gHFAd5cpbX1payzmsuKgkFVG/DusXMgiTnldEauaThDoVLNIa', 2, 0, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 16);
INSERT INTO korisnik (email, lozinka, sif_uloga, verzija_tokena, trenutak_stvaranja, trenutak_promjene, sif_slika_profila) VALUES ('user23@gmail.com', '$2a$10$KPj2gHFAd5cpbX1payzmsuKgkFVG/DusXMgiTnldEauaThDoVLNIa', 2, 0, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 17);
INSERT INTO korisnik (email, lozinka, sif_uloga, verzija_tokena, trenutak_stvaranja, trenutak_promjene, sif_slika_profila) VALUES ('user24@gmail.com', '$2a$10$KPj2gHFAd5cpbX1payzmsuKgkFVG/DusXMgiTnldEauaThDoVLNIa', 2, 0, NOW()::TIMESTAMP, NOW()::TIMESTAMP, NULL);
INSERT INTO korisnik (email, lozinka, sif_uloga, verzija_tokena, trenutak_stvaranja, trenutak_promjene, sif_slika_profila) VALUES ('user25@gmail.com', '$2a$10$KPj2gHFAd5cpbX1payzmsuKgkFVG/DusXMgiTnldEauaThDoVLNIa', 2, 0, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 18);
INSERT INTO korisnik (email, lozinka, sif_uloga, verzija_tokena, trenutak_stvaranja, trenutak_promjene, sif_slika_profila) VALUES ('user26@gmail.com', '$2a$10$KPj2gHFAd5cpbX1payzmsuKgkFVG/DusXMgiTnldEauaThDoVLNIa', 2, 0, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 19);
INSERT INTO korisnik (email, lozinka, sif_uloga, verzija_tokena, trenutak_stvaranja, trenutak_promjene, sif_slika_profila) VALUES ('user27@gmail.com', '$2a$10$KPj2gHFAd5cpbX1payzmsuKgkFVG/DusXMgiTnldEauaThDoVLNIa', 2, 0, NOW()::TIMESTAMP, NOW()::TIMESTAMP, NULL);
INSERT INTO korisnik (email, lozinka, sif_uloga, verzija_tokena, trenutak_stvaranja, trenutak_promjene, sif_slika_profila) VALUES ('user28@gmail.com', '$2a$10$KPj2gHFAd5cpbX1payzmsuKgkFVG/DusXMgiTnldEauaThDoVLNIa', 2, 0, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 20);
INSERT INTO korisnik (email, lozinka, sif_uloga, verzija_tokena, trenutak_stvaranja, trenutak_promjene, sif_slika_profila) VALUES ('user29@gmail.com', '$2a$10$KPj2gHFAd5cpbX1payzmsuKgkFVG/DusXMgiTnldEauaThDoVLNIa', 2, 0, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 21);
INSERT INTO korisnik (email, lozinka, sif_uloga, verzija_tokena, trenutak_stvaranja, trenutak_promjene, sif_slika_profila) VALUES ('user30@gmail.com', '$2a$10$KPj2gHFAd5cpbX1payzmsuKgkFVG/DusXMgiTnldEauaThDoVLNIa', 2, 0, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 22);

/* Računi servisa */
INSERT INTO korisnik (email, lozinka, sif_uloga, verzija_tokena, trenutak_stvaranja, trenutak_promjene, sif_slika_profila) VALUES ('servis1@gmail.com', '$2a$10$KPj2gHFAd5cpbX1payzmsuKgkFVG/DusXMgiTnldEauaThDoVLNIa', 3, 0, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 25);
INSERT INTO korisnik (email, lozinka, sif_uloga, verzija_tokena, trenutak_stvaranja, trenutak_promjene, sif_slika_profila) VALUES ('servis2@gmail.com', '$2a$10$KPj2gHFAd5cpbX1payzmsuKgkFVG/DusXMgiTnldEauaThDoVLNIa', 3, 0, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 26);
INSERT INTO korisnik (email, lozinka, sif_uloga, verzija_tokena, trenutak_stvaranja, trenutak_promjene, sif_slika_profila) VALUES ('servis3@gmail.com', '$2a$10$KPj2gHFAd5cpbX1payzmsuKgkFVG/DusXMgiTnldEauaThDoVLNIa', 3, 0, NOW()::TIMESTAMP, NOW()::TIMESTAMP, NULL);
INSERT INTO korisnik (email, lozinka, sif_uloga, verzija_tokena, trenutak_stvaranja, trenutak_promjene, sif_slika_profila) VALUES ('servis4@gmail.com', '$2a$10$KPj2gHFAd5cpbX1payzmsuKgkFVG/DusXMgiTnldEauaThDoVLNIa', 3, 0, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 27);
INSERT INTO korisnik (email, lozinka, sif_uloga, verzija_tokena, trenutak_stvaranja, trenutak_promjene, sif_slika_profila) VALUES ('servis5@gmail.com', '$2a$10$KPj2gHFAd5cpbX1payzmsuKgkFVG/DusXMgiTnldEauaThDoVLNIa', 3, 0, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 28);
INSERT INTO korisnik (email, lozinka, sif_uloga, verzija_tokena, trenutak_stvaranja, trenutak_promjene, sif_slika_profila) VALUES ('servis6@gmail.com', '$2a$10$KPj2gHFAd5cpbX1payzmsuKgkFVG/DusXMgiTnldEauaThDoVLNIa', 3, 0, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 29);
INSERT INTO korisnik (email, lozinka, sif_uloga, verzija_tokena, trenutak_stvaranja, trenutak_promjene, sif_slika_profila) VALUES ('servis7@gmail.com', '$2a$10$KPj2gHFAd5cpbX1payzmsuKgkFVG/DusXMgiTnldEauaThDoVLNIa', 3, 0, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 30);
INSERT INTO korisnik (email, lozinka, sif_uloga, verzija_tokena, trenutak_stvaranja, trenutak_promjene, sif_slika_profila) VALUES ('servis8@gmail.com', '$2a$10$KPj2gHFAd5cpbX1payzmsuKgkFVG/DusXMgiTnldEauaThDoVLNIa', 3, 0, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 49);
INSERT INTO korisnik (email, lozinka, sif_uloga, verzija_tokena, trenutak_stvaranja, trenutak_promjene, sif_slika_profila) VALUES ('servis9@gmail.com', '$2a$10$KPj2gHFAd5cpbX1payzmsuKgkFVG/DusXMgiTnldEauaThDoVLNIa', 3, 0, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 31);
INSERT INTO korisnik (email, lozinka, sif_uloga, verzija_tokena, trenutak_stvaranja, trenutak_promjene, sif_slika_profila) VALUES ('servis10@gmail.com', '$2a$10$KPj2gHFAd5cpbX1payzmsuKgkFVG/DusXMgiTnldEauaThDoVLNIa', 3, 0, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 32);
INSERT INTO korisnik (email, lozinka, sif_uloga, verzija_tokena, trenutak_stvaranja, trenutak_promjene, sif_slika_profila) VALUES ('servis11@gmail.com', '$2a$10$KPj2gHFAd5cpbX1payzmsuKgkFVG/DusXMgiTnldEauaThDoVLNIa', 3, 0, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 33);
INSERT INTO korisnik (email, lozinka, sif_uloga, verzija_tokena, trenutak_stvaranja, trenutak_promjene, sif_slika_profila) VALUES ('servis12@gmail.com', '$2a$10$KPj2gHFAd5cpbX1payzmsuKgkFVG/DusXMgiTnldEauaThDoVLNIa', 3, 0, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 34);
INSERT INTO korisnik (email, lozinka, sif_uloga, verzija_tokena, trenutak_stvaranja, trenutak_promjene, sif_slika_profila) VALUES ('servis13@gmail.com', '$2a$10$KPj2gHFAd5cpbX1payzmsuKgkFVG/DusXMgiTnldEauaThDoVLNIa', 3, 0, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 35);
INSERT INTO korisnik (email, lozinka, sif_uloga, verzija_tokena, trenutak_stvaranja, trenutak_promjene, sif_slika_profila) VALUES ('servis14@gmail.com', '$2a$10$KPj2gHFAd5cpbX1payzmsuKgkFVG/DusXMgiTnldEauaThDoVLNIa', 3, 0, NOW()::TIMESTAMP, NOW()::TIMESTAMP, NULL);
INSERT INTO korisnik (email, lozinka, sif_uloga, verzija_tokena, trenutak_stvaranja, trenutak_promjene, sif_slika_profila) VALUES ('servis15@gmail.com', '$2a$10$KPj2gHFAd5cpbX1payzmsuKgkFVG/DusXMgiTnldEauaThDoVLNIa', 3, 0, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 36);
INSERT INTO korisnik (email, lozinka, sif_uloga, verzija_tokena, trenutak_stvaranja, trenutak_promjene, sif_slika_profila) VALUES ('servis16@gmail.com', '$2a$10$KPj2gHFAd5cpbX1payzmsuKgkFVG/DusXMgiTnldEauaThDoVLNIa', 3, 0, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 37);
INSERT INTO korisnik (email, lozinka, sif_uloga, verzija_tokena, trenutak_stvaranja, trenutak_promjene, sif_slika_profila) VALUES ('servis17@gmail.com', '$2a$10$KPj2gHFAd5cpbX1payzmsuKgkFVG/DusXMgiTnldEauaThDoVLNIa', 3, 0, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 38);
INSERT INTO korisnik (email, lozinka, sif_uloga, verzija_tokena, trenutak_stvaranja, trenutak_promjene, sif_slika_profila) VALUES ('servis18@gmail.com', '$2a$10$KPj2gHFAd5cpbX1payzmsuKgkFVG/DusXMgiTnldEauaThDoVLNIa', 3, 0, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 39);
INSERT INTO korisnik (email, lozinka, sif_uloga, verzija_tokena, trenutak_stvaranja, trenutak_promjene, sif_slika_profila) VALUES ('servis19@gmail.com', '$2a$10$KPj2gHFAd5cpbX1payzmsuKgkFVG/DusXMgiTnldEauaThDoVLNIa', 3, 0, NOW()::TIMESTAMP, NOW()::TIMESTAMP, NULL);
INSERT INTO korisnik (email, lozinka, sif_uloga, verzija_tokena, trenutak_stvaranja, trenutak_promjene, sif_slika_profila) VALUES ('servis20@gmail.com', '$2a$10$KPj2gHFAd5cpbX1payzmsuKgkFVG/DusXMgiTnldEauaThDoVLNIa', 3, 0, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 40);
INSERT INTO korisnik (email, lozinka, sif_uloga, verzija_tokena, trenutak_stvaranja, trenutak_promjene, sif_slika_profila) VALUES ('servis21@gmail.com', '$2a$10$KPj2gHFAd5cpbX1payzmsuKgkFVG/DusXMgiTnldEauaThDoVLNIa', 3, 0, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 41);
INSERT INTO korisnik (email, lozinka, sif_uloga, verzija_tokena, trenutak_stvaranja, trenutak_promjene, sif_slika_profila) VALUES ('servis22@gmail.com', '$2a$10$KPj2gHFAd5cpbX1payzmsuKgkFVG/DusXMgiTnldEauaThDoVLNIa', 3, 0, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 42);
INSERT INTO korisnik (email, lozinka, sif_uloga, verzija_tokena, trenutak_stvaranja, trenutak_promjene, sif_slika_profila) VALUES ('servis23@gmail.com', '$2a$10$KPj2gHFAd5cpbX1payzmsuKgkFVG/DusXMgiTnldEauaThDoVLNIa', 3, 0, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 43);
INSERT INTO korisnik (email, lozinka, sif_uloga, verzija_tokena, trenutak_stvaranja, trenutak_promjene, sif_slika_profila) VALUES ('servis24@gmail.com', '$2a$10$KPj2gHFAd5cpbX1payzmsuKgkFVG/DusXMgiTnldEauaThDoVLNIa', 3, 0, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 44);
INSERT INTO korisnik (email, lozinka, sif_uloga, verzija_tokena, trenutak_stvaranja, trenutak_promjene, sif_slika_profila) VALUES ('servis25@gmail.com', '$2a$10$KPj2gHFAd5cpbX1payzmsuKgkFVG/DusXMgiTnldEauaThDoVLNIa', 3, 0, NOW()::TIMESTAMP, NOW()::TIMESTAMP, NULL);
INSERT INTO korisnik (email, lozinka, sif_uloga, verzija_tokena, trenutak_stvaranja, trenutak_promjene, sif_slika_profila) VALUES ('servis26@gmail.com', '$2a$10$KPj2gHFAd5cpbX1payzmsuKgkFVG/DusXMgiTnldEauaThDoVLNIa', 3, 0, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 45);
INSERT INTO korisnik (email, lozinka, sif_uloga, verzija_tokena, trenutak_stvaranja, trenutak_promjene, sif_slika_profila) VALUES ('servis27@gmail.com', '$2a$10$KPj2gHFAd5cpbX1payzmsuKgkFVG/DusXMgiTnldEauaThDoVLNIa', 3, 0, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 46);
INSERT INTO korisnik (email, lozinka, sif_uloga, verzija_tokena, trenutak_stvaranja, trenutak_promjene, sif_slika_profila) VALUES ('servis28@gmail.com', '$2a$10$KPj2gHFAd5cpbX1payzmsuKgkFVG/DusXMgiTnldEauaThDoVLNIa', 3, 0, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 47);
INSERT INTO korisnik (email, lozinka, sif_uloga, verzija_tokena, trenutak_stvaranja, trenutak_promjene, sif_slika_profila) VALUES ('servis29@gmail.com', '$2a$10$KPj2gHFAd5cpbX1payzmsuKgkFVG/DusXMgiTnldEauaThDoVLNIa', 3, 0, NOW()::TIMESTAMP, NOW()::TIMESTAMP, NULL);
INSERT INTO korisnik (email, lozinka, sif_uloga, verzija_tokena, trenutak_stvaranja, trenutak_promjene, sif_slika_profila) VALUES ('servis30@gmail.com', '$2a$10$KPj2gHFAd5cpbX1payzmsuKgkFVG/DusXMgiTnldEauaThDoVLNIa', 3, 0, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 48);

/* Podatci običnih korisnika */
INSERT INTO osoba (ime, prezime, sif_korisnik, trenutak_stvaranja, trenutak_promjene) VALUES ('Niko', 'Dragović', 1, NOW()::TIMESTAMP, NOW()::TIMESTAMP);
INSERT INTO osoba (ime, prezime, sif_korisnik, trenutak_stvaranja, trenutak_promjene) VALUES ('Lukas', 'Adamić', 2, NOW()::TIMESTAMP, NOW()::TIMESTAMP);
INSERT INTO osoba (ime, prezime, sif_korisnik, trenutak_stvaranja, trenutak_promjene) VALUES ('Kristijan', 'Brož', 3, NOW()::TIMESTAMP, NOW()::TIMESTAMP);
INSERT INTO osoba (ime, prezime, sif_korisnik, trenutak_stvaranja, trenutak_promjene) VALUES ('Sven', 'Knežević', 4, NOW()::TIMESTAMP, NOW()::TIMESTAMP);
INSERT INTO osoba (ime, prezime, sif_korisnik, trenutak_stvaranja, trenutak_promjene) VALUES ('Dora', 'Dora', 5, NOW()::TIMESTAMP, NOW()::TIMESTAMP);
INSERT INTO osoba (ime, prezime, sif_korisnik, trenutak_stvaranja, trenutak_promjene) VALUES ('Dunja', 'Blažević', 6, NOW()::TIMESTAMP, NOW()::TIMESTAMP);
INSERT INTO osoba (ime, prezime, sif_korisnik, trenutak_stvaranja, trenutak_promjene) VALUES ('Jelena', 'Dragović', 7, NOW()::TIMESTAMP, NOW()::TIMESTAMP);
INSERT INTO osoba (ime, prezime, sif_korisnik, trenutak_stvaranja, trenutak_promjene) VALUES ('Dino', 'Neretljak', 8, NOW()::TIMESTAMP, NOW()::TIMESTAMP);
INSERT INTO osoba (ime, prezime, sif_korisnik, trenutak_stvaranja, trenutak_promjene) VALUES ('Nino', 'Srna', 9, NOW()::TIMESTAMP, NOW()::TIMESTAMP);
INSERT INTO osoba (ime, prezime, sif_korisnik, trenutak_stvaranja, trenutak_promjene) VALUES ('Eva', 'Petrović', 10, NOW()::TIMESTAMP, NOW()::TIMESTAMP);
INSERT INTO osoba (ime, prezime, sif_korisnik, trenutak_stvaranja, trenutak_promjene) VALUES ('Leon', 'Marušić', 11, NOW()::TIMESTAMP, NOW()::TIMESTAMP);
INSERT INTO osoba (ime, prezime, sif_korisnik, trenutak_stvaranja, trenutak_promjene) VALUES ('Nino', 'Perić', 12, NOW()::TIMESTAMP, NOW()::TIMESTAMP);
INSERT INTO osoba (ime, prezime, sif_korisnik, trenutak_stvaranja, trenutak_promjene) VALUES ('Marin', 'Knežević', 13, NOW()::TIMESTAMP, NOW()::TIMESTAMP);
INSERT INTO osoba (ime, prezime, sif_korisnik, trenutak_stvaranja, trenutak_promjene) VALUES ('Vanesa', 'Bogdanović', 14, NOW()::TIMESTAMP, NOW()::TIMESTAMP);
INSERT INTO osoba (ime, prezime, sif_korisnik, trenutak_stvaranja, trenutak_promjene) VALUES ('Mila', 'Radić', 15, NOW()::TIMESTAMP, NOW()::TIMESTAMP);
INSERT INTO osoba (ime, prezime, sif_korisnik, trenutak_stvaranja, trenutak_promjene) VALUES ('Tea', 'Mlakar', 16, NOW()::TIMESTAMP, NOW()::TIMESTAMP);
INSERT INTO osoba (ime, prezime, sif_korisnik, trenutak_stvaranja, trenutak_promjene) VALUES ('Martina', 'Tomčić', 17, NOW()::TIMESTAMP, NOW()::TIMESTAMP);
INSERT INTO osoba (ime, prezime, sif_korisnik, trenutak_stvaranja, trenutak_promjene) VALUES ('Nika', 'Blažević', 18, NOW()::TIMESTAMP, NOW()::TIMESTAMP);
INSERT INTO osoba (ime, prezime, sif_korisnik, trenutak_stvaranja, trenutak_promjene) VALUES ('Bruno', 'Kovač', 19, NOW()::TIMESTAMP, NOW()::TIMESTAMP);
INSERT INTO osoba (ime, prezime, sif_korisnik, trenutak_stvaranja, trenutak_promjene) VALUES ('Tomislav', 'Ćorluka', 20, NOW()::TIMESTAMP, NOW()::TIMESTAMP);
INSERT INTO osoba (ime, prezime, sif_korisnik, trenutak_stvaranja, trenutak_promjene) VALUES ('Ivana', 'Blažević', 21, NOW()::TIMESTAMP, NOW()::TIMESTAMP);
INSERT INTO osoba (ime, prezime, sif_korisnik, trenutak_stvaranja, trenutak_promjene) VALUES ('Lena', 'Pavletić', 22, NOW()::TIMESTAMP, NOW()::TIMESTAMP);
INSERT INTO osoba (ime, prezime, sif_korisnik, trenutak_stvaranja, trenutak_promjene) VALUES ('Katja', 'Stanković', 23, NOW()::TIMESTAMP, NOW()::TIMESTAMP);
INSERT INTO osoba (ime, prezime, sif_korisnik, trenutak_stvaranja, trenutak_promjene) VALUES ('Marina', 'Juriša', 24, NOW()::TIMESTAMP, NOW()::TIMESTAMP);
INSERT INTO osoba (ime, prezime, sif_korisnik, trenutak_stvaranja, trenutak_promjene) VALUES ('Vid', 'Vlašić', 25, NOW()::TIMESTAMP, NOW()::TIMESTAMP);
INSERT INTO osoba (ime, prezime, sif_korisnik, trenutak_stvaranja, trenutak_promjene) VALUES ('Dorotea', 'Maras', 26, NOW()::TIMESTAMP, NOW()::TIMESTAMP);
INSERT INTO osoba (ime, prezime, sif_korisnik, trenutak_stvaranja, trenutak_promjene) VALUES ('Lukas', 'Vlašić', 27, NOW()::TIMESTAMP, NOW()::TIMESTAMP);
INSERT INTO osoba (ime, prezime, sif_korisnik, trenutak_stvaranja, trenutak_promjene) VALUES ('Marija', 'Kovačić', 28, NOW()::TIMESTAMP, NOW()::TIMESTAMP);
INSERT INTO osoba (ime, prezime, sif_korisnik, trenutak_stvaranja, trenutak_promjene) VALUES ('Dora', 'Vincetić', 29, NOW()::TIMESTAMP, NOW()::TIMESTAMP);
INSERT INTO osoba (ime, prezime, sif_korisnik, trenutak_stvaranja, trenutak_promjene) VALUES ('Ella', 'Adamić', 30, NOW()::TIMESTAMP, NOW()::TIMESTAMP);

/* Podaci servisa */
INSERT INTO servis (naziv_servis, oib, telefon, adresa, web_lokacija, opis, sif_mjesto, sif_korisnik, trenutak_stvaranja, trenutak_promjene) VALUES ('servicell', '84483336690', '+385-915-554-158', 'Donje Svetice 89', 'Google.com', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras nec odio congue, vestibulum nisi at, ultrices dui. Ut non eleifend ligula. ', 1, 31, NOW()::TIMESTAMP, NOW()::TIMESTAMP);
INSERT INTO servis (naziv_servis, oib, telefon, adresa, web_lokacija, opis, sif_mjesto, sif_korisnik, trenutak_stvaranja, trenutak_promjene) VALUES ('SERVICEF', '79578869924', '+385-995-555-192', 'Medvedski breg 48', 'YouTube.com', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras nec odio congue, vestibulum nisi at, ultrices dui. Ut non eleifend ligula. Aliquam ut arcu id lectus suscipit dignissim vitae sed risus.', 1, 32, NOW()::TIMESTAMP, NOW()::TIMESTAMP);
INSERT INTO servis (naziv_servis, oib, telefon, adresa, web_lokacija, opis, sif_mjesto, sif_korisnik, trenutak_stvaranja, trenutak_promjene) VALUES ('plance', '15580450400', '+385-995-550-187', 'Pantovčak 125b', 'Facebook.com', NULL, 1, 33, NOW()::TIMESTAMP, NOW()::TIMESTAMP);
INSERT INTO servis (naziv_servis, oib, telefon, adresa, web_lokacija, opis, sif_mjesto, sif_korisnik, trenutak_stvaranja, trenutak_promjene) VALUES ('metail', '36323121804', '+385-925-553-224', 'Stupnička 2', 'Twitter.com', 'Lorem ipsum dolor sit amet,', 1, 34, NOW()::TIMESTAMP, NOW()::TIMESTAMP);
INSERT INTO servis (naziv_servis, oib, telefon, adresa, web_lokacija, opis, sif_mjesto, sif_korisnik, trenutak_stvaranja, trenutak_promjene) VALUES ('portise', '12771764391', '+385-925-551-174', 'Hrgovići 51', 'Instagram.com', 'Proin euismod mattis ipsum ac scelerisque.', 1, 35, NOW()::TIMESTAMP, NOW()::TIMESTAMP);
INSERT INTO servis (naziv_servis, oib, telefon, adresa, web_lokacija, opis, sif_mjesto, sif_korisnik, trenutak_stvaranja, trenutak_promjene) VALUES ('fination', '61401765974', '+385-995-550-617', 'Ruđera Boškovića 30', 'Baidu.com', NULL, 123, 36, NOW()::TIMESTAMP, NOW()::TIMESTAMP);
INSERT INTO servis (naziv_servis, oib, telefon, adresa, web_lokacija, opis, sif_mjesto, sif_korisnik, trenutak_stvaranja, trenutak_promjene) VALUES ('vality', '25094870777', '+385-925-556-680', 'Tijardovićeva 4', NULL, 'Vestibulum venenatis lacus in ante facilisis, ac tincidunt mi dapibus.', 123, 37, NOW()::TIMESTAMP, NOW()::TIMESTAMP);
INSERT INTO servis (naziv_servis, oib, telefon, adresa, web_lokacija, opis, sif_mjesto, sif_korisnik, trenutak_stvaranja, trenutak_promjene) VALUES ('UNITYAID', '79293064758', '+385-985-552-551', 'Velebitska 27', 'Wikipedia.org', NULL, 123, 38, NOW()::TIMESTAMP, NOW()::TIMESTAMP);
INSERT INTO servis (naziv_servis, oib, telefon, adresa, web_lokacija, opis, sif_mjesto, sif_korisnik, trenutak_stvaranja, trenutak_promjene) VALUES ('PARTFIRE', '14278598125', '+385-955-550-071', 'Kapucinska 25', NULL, 'Vestibulum vitae dui dolor. Nam vel placerat magna. Sed nec molestie enim. Sed tristique placerat consequat. Donec urna sapien, faucibus ut mi vitae, dignissim lobortis dolor. Integer cursus malesuada tortor, sed dapibus orci maximus eget. ', 338, 39, NOW()::TIMESTAMP, NOW()::TIMESTAMP);
INSERT INTO servis (naziv_servis, oib, telefon, adresa, web_lokacija, opis, sif_mjesto, sif_korisnik, trenutak_stvaranja, trenutak_promjene) VALUES ('cservice', '56529541917', '+385-925-551-836', 'Korčulanska 1', 'Yandex.ru', NULL, 338, 40, NOW()::TIMESTAMP, NOW()::TIMESTAMP);
INSERT INTO servis (naziv_servis, oib, telefon, adresa, web_lokacija, opis, sif_mjesto, sif_korisnik, trenutak_stvaranja, trenutak_promjene) VALUES ('workcare', '76649061241', '+385-955-552-748', 'J. Gojkovića 23', 'Yahoo.com', 'Fusce a vestibulum mauris, in malesuada risus.', 338, 41, NOW()::TIMESTAMP, NOW()::TIMESTAMP);
INSERT INTO servis (naziv_servis, oib, telefon, adresa, web_lokacija, opis, sif_mjesto, sif_korisnik, trenutak_stvaranja, trenutak_promjene) VALUES ('servicei', '39643821741', '+385-995-551-216', 'Kapucinska 21', 'Amazon.com', NULL, 338, 42, NOW()::TIMESTAMP, NOW()::TIMESTAMP);
INSERT INTO servis (naziv_servis, oib, telefon, adresa, web_lokacija, opis, sif_mjesto, sif_korisnik, trenutak_stvaranja, trenutak_promjene) VALUES ('SERVICURE', '11016199997', '+385-995-556-209', 'Trenkova 14',  NULL, NULL, 563, 43, NOW()::TIMESTAMP, NOW()::TIMESTAMP);
INSERT INTO servis (naziv_servis, oib, telefon, adresa, web_lokacija, opis, sif_mjesto, sif_korisnik, trenutak_stvaranja, trenutak_promjene) VALUES ('MOBILITE', '23984136948', '+385-955-556-776', 'Jurkovićeva 27', 'Live.com', NULL, 563, 44, NOW()::TIMESTAMP, NOW()::TIMESTAMP);
INSERT INTO servis (naziv_servis, oib, telefon, adresa, web_lokacija, opis, sif_mjesto, sif_korisnik, trenutak_stvaranja, trenutak_promjene) VALUES ('minance', '16152991631', '+385-915-551-439', 'Zagrebačka 94', 'Vk.com', 'Mauris dignissim sollicitudin lacus ut consectetur. ', 563, 45, NOW()::TIMESTAMP, NOW()::TIMESTAMP);
INSERT INTO servis (naziv_servis, oib, telefon, adresa, web_lokacija, opis, sif_mjesto, sif_korisnik, trenutak_stvaranja, trenutak_promjene) VALUES ('ServiceK', '16413060118', '+385-915-554-008', 'Maršala Tita 102', 'Yahoo.co.jp', NULL, 7, 46, NOW()::TIMESTAMP, NOW()::TIMESTAMP);
INSERT INTO servis (naziv_servis, oib, telefon, adresa, web_lokacija, opis, sif_mjesto, sif_korisnik, trenutak_stvaranja, trenutak_promjene) VALUES ('cartise', '09751509306', '+385-985-556-590', 'Trg žrtava fašizma 17', 'Zoom.us', NULL, 7, 47, NOW()::TIMESTAMP, NOW()::TIMESTAMP);
INSERT INTO servis (naziv_servis, oib, telefon, adresa, web_lokacija, opis, sif_mjesto, sif_korisnik, trenutak_stvaranja, trenutak_promjene) VALUES ('Servance', '29224505447', '+385-955-556-387', 'Draškovića Janka 72', 'Netflix.com', 'Pellentesque pharetra magna et feugiat cursus.', 7, 48, NOW()::TIMESTAMP, NOW()::TIMESTAMP);
INSERT INTO servis (naziv_servis, oib, telefon, adresa, web_lokacija, opis, sif_mjesto, sif_korisnik, trenutak_stvaranja, trenutak_promjene) VALUES ('socialty', '62324576359', '+385-915-554-336', 'Ulica maršala Tita 85', 'Reddit.com', 'Nam luctus facilisis neque ac vehicula.', 7, 49, NOW()::TIMESTAMP, NOW()::TIMESTAMP);
INSERT INTO servis (naziv_servis, oib, telefon, adresa, web_lokacija, opis, sif_mjesto, sif_korisnik, trenutak_stvaranja, trenutak_promjene) VALUES ('Resport', '01406197153', '+385-975-558-569', 'Osječka 14', NULL, NULL,  798, 50, NOW()::TIMESTAMP, NOW()::TIMESTAMP);
INSERT INTO servis (naziv_servis, oib, telefon, adresa, web_lokacija, opis, sif_mjesto, sif_korisnik, trenutak_stvaranja, trenutak_promjene) VALUES ('Servicee', '99641246186', '+385-985-557-884', 'Ante Starčevića 5', 'Office.com', NULL, 798, 51, NOW()::TIMESTAMP, NOW()::TIMESTAMP);
INSERT INTO servis (naziv_servis, oib, telefon, adresa, web_lokacija, opis, sif_mjesto, sif_korisnik, trenutak_stvaranja, trenutak_promjene) VALUES ('servicean', '96294770333', '+385-915-555-692', 'Lošinjska 16', 'Discord.com', 'Donec iaculis, justo a dictum bibendum, urna odio blandit magna, a vulputate enim magna ut ligula.', 798, 52, NOW()::TIMESTAMP, NOW()::TIMESTAMP);
INSERT INTO servis (naziv_servis, oib, telefon, adresa, web_lokacija, opis, sif_mjesto, sif_korisnik, trenutak_stvaranja, trenutak_promjene) VALUES ('FSERVICE', '89871519898', '+385-975-556-313', 'Frana Galovića bb', 'Naver.com', 'Vestibulum mollis a orci in auctor.', 762, 53, NOW()::TIMESTAMP, NOW()::TIMESTAMP);
INSERT INTO servis (naziv_servis, oib, telefon, adresa, web_lokacija, opis, sif_mjesto, sif_korisnik, trenutak_stvaranja, trenutak_promjene) VALUES ('CUSTORE', '84379508654', '+385-955-559-564', 'Magistratska ulica 11', 'LinkedIn.com', NULL, 762, 54, NOW()::TIMESTAMP, NOW()::TIMESTAMP);
INSERT INTO servis (naziv_servis, oib, telefon, adresa, web_lokacija, opis, sif_mjesto, sif_korisnik, trenutak_stvaranja, trenutak_promjene) VALUES ('RENTDUTY', '19034452083', '+385-975-556-406', 'Podgora 118a', 'WhatsApp.com', 'Ut ac lorem in elit lacinia tristique. Etiam dapibus volutpat justo, id tempus erat rhoncus et. Aenean mattis vulputate est et venenatis. ', 762, 55, NOW()::TIMESTAMP, NOW()::TIMESTAMP);
INSERT INTO servis (naziv_servis, oib, telefon, adresa, web_lokacija, opis, sif_mjesto, sif_korisnik, trenutak_stvaranja, trenutak_promjene) VALUES ('pservice', '88815524280', '+385-915-552-736', 'Kardinala Stepinca 1', 'TikTok.com', NULL, 762, 56, NOW()::TIMESTAMP, NOW()::TIMESTAMP);
INSERT INTO servis (naziv_servis, oib, telefon, adresa, web_lokacija, opis, sif_mjesto, sif_korisnik, trenutak_stvaranja, trenutak_promjene) VALUES ('custory', '43065759440', '+385-925-553-504', 'Križanićeva 30', 'Pinterest.com', 'Vivamus accumsan et nisl interdum molestie. Mauris dignissim sollicitudin lacus ut consectetur.', 683, 57, NOW()::TIMESTAMP, NOW()::TIMESTAMP);
INSERT INTO servis (naziv_servis, oib, telefon, adresa, web_lokacija, opis, sif_mjesto, sif_korisnik, trenutak_stvaranja, trenutak_promjene) VALUES ('modecare', '94545051450', '+385-955-557-272', 'Donje Pokupje 2', 'Google.com.br', NULL, 683, 58, NOW()::TIMESTAMP, NOW()::TIMESTAMP);
INSERT INTO servis (naziv_servis, oib, telefon, adresa, web_lokacija, opis, sif_mjesto, sif_korisnik, trenutak_stvaranja, trenutak_promjene) VALUES ('Servicev', '45363782197', '+385-975-554-488', 'Kneza Trpimira b.b.', 'Ebay.com', 'Donec iaculis, justo a dictum bibendum, urna odio blandit magna, a vulputate enim magna ut ligula.', 278, 59, NOW()::TIMESTAMP, NOW()::TIMESTAMP);
INSERT INTO servis (naziv_servis, oib, telefon, adresa, web_lokacija, opis, sif_mjesto, sif_korisnik, trenutak_stvaranja, trenutak_promjene) VALUES ('Vsatic', '96906852095', '+385-955-550-024', 'Put Petrića 43', 'Microsoft.com', NULL, 278, 60, NOW()::TIMESTAMP, NOW()::TIMESTAMP);

/* Kategorije kvarova koje popravljaju serviseri */
INSERT INTO servis_fault_categories_kategorija_kvara VALUES (1, 7);
INSERT INTO servis_fault_categories_kategorija_kvara VALUES (1, 8);
INSERT INTO servis_fault_categories_kategorija_kvara VALUES (1, 9);
INSERT INTO servis_fault_categories_kategorija_kvara VALUES (1, 10);
INSERT INTO servis_fault_categories_kategorija_kvara VALUES (2, 13);
INSERT INTO servis_fault_categories_kategorija_kvara VALUES (2, 14);
INSERT INTO servis_fault_categories_kategorija_kvara VALUES (2, 15);
INSERT INTO servis_fault_categories_kategorija_kvara VALUES (3, 16);
INSERT INTO servis_fault_categories_kategorija_kvara VALUES (3, 17);
INSERT INTO servis_fault_categories_kategorija_kvara VALUES (5, 16);
INSERT INTO servis_fault_categories_kategorija_kvara VALUES (5, 17);
INSERT INTO servis_fault_categories_kategorija_kvara VALUES (5, 18);
INSERT INTO servis_fault_categories_kategorija_kvara VALUES (6, 7);
INSERT INTO servis_fault_categories_kategorija_kvara VALUES (6, 8);
INSERT INTO servis_fault_categories_kategorija_kvara VALUES (6, 12);
INSERT INTO servis_fault_categories_kategorija_kvara VALUES (7, 23);
INSERT INTO servis_fault_categories_kategorija_kvara VALUES (7, 22);
INSERT INTO servis_fault_categories_kategorija_kvara VALUES (7, 21);
INSERT INTO servis_fault_categories_kategorija_kvara VALUES (8, 16);
INSERT INTO servis_fault_categories_kategorija_kvara VALUES (8, 17);
INSERT INTO servis_fault_categories_kategorija_kvara VALUES (9, 31);
INSERT INTO servis_fault_categories_kategorija_kvara VALUES (9, 30);
INSERT INTO servis_fault_categories_kategorija_kvara VALUES (9, 35);
INSERT INTO servis_fault_categories_kategorija_kvara VALUES (10, 27);
INSERT INTO servis_fault_categories_kategorija_kvara VALUES (10, 31);
INSERT INTO servis_fault_categories_kategorija_kvara VALUES (10, 35);
INSERT INTO servis_fault_categories_kategorija_kvara VALUES (11, 35);
INSERT INTO servis_fault_categories_kategorija_kvara VALUES (11, 27);
INSERT INTO servis_fault_categories_kategorija_kvara VALUES (11, 39);
INSERT INTO servis_fault_categories_kategorija_kvara VALUES (13, 40);
INSERT INTO servis_fault_categories_kategorija_kvara VALUES (13, 41);
INSERT INTO servis_fault_categories_kategorija_kvara VALUES (13, 42);
INSERT INTO servis_fault_categories_kategorija_kvara VALUES (13, 45);
INSERT INTO servis_fault_categories_kategorija_kvara VALUES (14, 40);
INSERT INTO servis_fault_categories_kategorija_kvara VALUES (14, 46);
INSERT INTO servis_fault_categories_kategorija_kvara VALUES (14, 42);
INSERT INTO servis_fault_categories_kategorija_kvara VALUES (15, 47);
INSERT INTO servis_fault_categories_kategorija_kvara VALUES (15, 42);
INSERT INTO servis_fault_categories_kategorija_kvara VALUES (16, 48);
INSERT INTO servis_fault_categories_kategorija_kvara VALUES (16, 47);
INSERT INTO servis_fault_categories_kategorija_kvara VALUES (16, 43);
INSERT INTO servis_fault_categories_kategorija_kvara VALUES (17, 43);
INSERT INTO servis_fault_categories_kategorija_kvara VALUES (17, 46);
INSERT INTO servis_fault_categories_kategorija_kvara VALUES (18, 12);
INSERT INTO servis_fault_categories_kategorija_kvara VALUES (18, 11);
INSERT INTO servis_fault_categories_kategorija_kvara VALUES (18, 13);
INSERT INTO servis_fault_categories_kategorija_kvara VALUES (19, 7);
INSERT INTO servis_fault_categories_kategorija_kvara VALUES (19, 16);
INSERT INTO servis_fault_categories_kategorija_kvara VALUES (19, 17);
INSERT INTO servis_fault_categories_kategorija_kvara VALUES (20, 16);
INSERT INTO servis_fault_categories_kategorija_kvara VALUES (20, 19);
INSERT INTO servis_fault_categories_kategorija_kvara VALUES (20, 20);
INSERT INTO servis_fault_categories_kategorija_kvara VALUES (21, 24);
INSERT INTO servis_fault_categories_kategorija_kvara VALUES (21, 23);
INSERT INTO servis_fault_categories_kategorija_kvara VALUES (22, 20);
INSERT INTO servis_fault_categories_kategorija_kvara VALUES (22, 21);
INSERT INTO servis_fault_categories_kategorija_kvara VALUES (22, 23);
INSERT INTO servis_fault_categories_kategorija_kvara VALUES (23, 34);
INSERT INTO servis_fault_categories_kategorija_kvara VALUES (23, 35);
INSERT INTO servis_fault_categories_kategorija_kvara VALUES (24, 27);
INSERT INTO servis_fault_categories_kategorija_kvara VALUES (24, 28);
INSERT INTO servis_fault_categories_kategorija_kvara VALUES (24, 29);
INSERT INTO servis_fault_categories_kategorija_kvara VALUES (24, 30);
INSERT INTO servis_fault_categories_kategorija_kvara VALUES (24, 31);
INSERT INTO servis_fault_categories_kategorija_kvara VALUES (25, 36);
INSERT INTO servis_fault_categories_kategorija_kvara VALUES (25, 37);
INSERT INTO servis_fault_categories_kategorija_kvara VALUES (25, 38);
INSERT INTO servis_fault_categories_kategorija_kvara VALUES (27, 42);
INSERT INTO servis_fault_categories_kategorija_kvara VALUES (27, 41);
INSERT INTO servis_fault_categories_kategorija_kvara VALUES (27, 40);
INSERT INTO servis_fault_categories_kategorija_kvara VALUES (28, 46);
INSERT INTO servis_fault_categories_kategorija_kvara VALUES (28, 47);
INSERT INTO servis_fault_categories_kategorija_kvara VALUES (29, 40);
INSERT INTO servis_fault_categories_kategorija_kvara VALUES (29, 41);

/* Recenzije */
INSERT INTO recenzija (sadrzaj, ocjena, trenutak_stvaranja, trenutak_promjene, sif_osoba, sif_servis) VALUES ('Semper risus in hendrerit gravida rutrum.', 4, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 28, 1);
INSERT INTO recenzija (sadrzaj, ocjena, trenutak_stvaranja, trenutak_promjene, sif_osoba, sif_servis) VALUES ('Semper risus in hendrerit gravida rutrum.', 1, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 18, 2);
INSERT INTO recenzija (sadrzaj, ocjena, trenutak_stvaranja, trenutak_promjene, sif_osoba, sif_servis) VALUES ('Consectetur adipiscing elit pellentesque habitant.', 4, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 4, 2);
INSERT INTO recenzija (sadrzaj, ocjena, trenutak_stvaranja, trenutak_promjene, sif_osoba, sif_servis) VALUES ('Volutpat consequat mauris nunc congue nisi vitae.', 2, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 29, 3);
INSERT INTO recenzija (sadrzaj, ocjena, trenutak_stvaranja, trenutak_promjene, sif_osoba, sif_servis) VALUES ('Venenatis a condimentum vitae sapien. Quisque egestas diam in arcu cursus.', 3, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 10, 3);
INSERT INTO recenzija (sadrzaj, ocjena, trenutak_stvaranja, trenutak_promjene, sif_osoba, sif_servis) VALUES ('Urna et pharetra pharetra massa massa ultricies. Odio ut sem nulla pharetra diam sit amet.', 2, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 9, 4);
INSERT INTO recenzija (sadrzaj, ocjena, trenutak_stvaranja, trenutak_promjene, sif_osoba, sif_servis) VALUES ('Leo duis ut diam quam nulla porttitor massa id neque. Consectetur lorem donec massa sapien faucibus et molestie ac feugiat.', 2, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 27, 4);
INSERT INTO recenzija (sadrzaj, ocjena, trenutak_stvaranja, trenutak_promjene, sif_osoba, sif_servis) VALUES ('Leo duis ut diam quam nulla porttitor massa id neque. Consectetur lorem donec massa sapien faucibus et molestie ac feugiat.', 4, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 10, 5);
INSERT INTO recenzija (sadrzaj, ocjena, trenutak_stvaranja, trenutak_promjene, sif_osoba, sif_servis) VALUES ('Volutpat consequat mauris nunc congue nisi vitae.', 3, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 2, 5);
INSERT INTO recenzija (sadrzaj, ocjena, trenutak_stvaranja, trenutak_promjene, sif_osoba, sif_servis) VALUES ('Urna et pharetra pharetra massa massa ultricies. Odio ut sem nulla pharetra diam sit amet.', 2, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 10, 6);
INSERT INTO recenzija (sadrzaj, ocjena, trenutak_stvaranja, trenutak_promjene, sif_osoba, sif_servis) VALUES ('Volutpat ac tincidunt vitae semper.', 4, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 20, 7);
INSERT INTO recenzija (sadrzaj, ocjena, trenutak_stvaranja, trenutak_promjene, sif_osoba, sif_servis) VALUES ('Faucibus in ornare quam viverra orci sagittis eu volutpat.', 2, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 21, 8);
INSERT INTO recenzija (sadrzaj, ocjena, trenutak_stvaranja, trenutak_promjene, sif_osoba, sif_servis) VALUES ('Volutpat ac tincidunt vitae semper.', 2, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 22, 9);
INSERT INTO recenzija (sadrzaj, ocjena, trenutak_stvaranja, trenutak_promjene, sif_osoba, sif_servis) VALUES ('Urna et pharetra pharetra massa massa ultricies. Odio ut sem nulla pharetra diam sit amet.', 1, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 8, 10);
INSERT INTO recenzija (sadrzaj, ocjena, trenutak_stvaranja, trenutak_promjene, sif_osoba, sif_servis) VALUES ('Volutpat consequat mauris nunc congue nisi vitae.', 4, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 25, 10);
INSERT INTO recenzija (sadrzaj, ocjena, trenutak_stvaranja, trenutak_promjene, sif_osoba, sif_servis) VALUES ('Sit amet dictum sit amet justo donec enim diam vulputate.', 3, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 12, 11);
INSERT INTO recenzija (sadrzaj, ocjena, trenutak_stvaranja, trenutak_promjene, sif_osoba, sif_servis) VALUES ('Faucibus scelerisque eleifend donec pretium vulputate sapien nec.', 4, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 25, 11);
INSERT INTO recenzija (sadrzaj, ocjena, trenutak_stvaranja, trenutak_promjene, sif_osoba, sif_servis) VALUES ('Urna et pharetra pharetra massa massa ultricies. Odio ut sem nulla pharetra diam sit amet.', 5, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 15, 11);
INSERT INTO recenzija (sadrzaj, ocjena, trenutak_stvaranja, trenutak_promjene, sif_osoba, sif_servis) VALUES ('Urna et pharetra pharetra massa massa ultricies. Odio ut sem nulla pharetra diam sit amet.', 5, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 3, 13);
INSERT INTO recenzija (sadrzaj, ocjena, trenutak_stvaranja, trenutak_promjene, sif_osoba, sif_servis) VALUES ('Volutpat consequat mauris nunc congue nisi vitae.', 1, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 12, 13);
INSERT INTO recenzija (sadrzaj, ocjena, trenutak_stvaranja, trenutak_promjene, sif_osoba, sif_servis) VALUES ('Faucibus in ornare quam viverra orci sagittis eu volutpat.', 3, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 27, 14);
INSERT INTO recenzija (sadrzaj, ocjena, trenutak_stvaranja, trenutak_promjene, sif_osoba, sif_servis) VALUES ('Venenatis a condimentum vitae sapien. Quisque egestas diam in arcu cursus.', 1, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 11, 14);
INSERT INTO recenzija (sadrzaj, ocjena, trenutak_stvaranja, trenutak_promjene, sif_osoba, sif_servis) VALUES ('Semper risus in hendrerit gravida rutrum.', 3, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 27, 15);
INSERT INTO recenzija (sadrzaj, ocjena, trenutak_stvaranja, trenutak_promjene, sif_osoba, sif_servis) VALUES ('Volutpat ac tincidunt vitae semper.', 4, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 24, 15);
INSERT INTO recenzija (sadrzaj, ocjena, trenutak_stvaranja, trenutak_promjene, sif_osoba, sif_servis) VALUES ('Volutpat ac tincidunt vitae semper.', 4, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 14, 17);
INSERT INTO recenzija (sadrzaj, ocjena, trenutak_stvaranja, trenutak_promjene, sif_osoba, sif_servis) VALUES ('Consectetur adipiscing elit pellentesque habitant.', 2, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 19, 17);
INSERT INTO recenzija (sadrzaj, ocjena, trenutak_stvaranja, trenutak_promjene, sif_osoba, sif_servis) VALUES ('Pretium lectus quam id leo in vitae turpis massa.', 1, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 13, 18);
INSERT INTO recenzija (sadrzaj, ocjena, trenutak_stvaranja, trenutak_promjene, sif_osoba, sif_servis) VALUES ('Semper risus in hendrerit gravida rutrum.', 4, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 19, 18);
INSERT INTO recenzija (sadrzaj, ocjena, trenutak_stvaranja, trenutak_promjene, sif_osoba, sif_servis) VALUES ('Volutpat ac tincidunt vitae semper.', 1, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 24, 18);
INSERT INTO recenzija (sadrzaj, ocjena, trenutak_stvaranja, trenutak_promjene, sif_osoba, sif_servis) VALUES ('Venenatis a condimentum vitae sapien. Quisque egestas diam in arcu cursus.', 2, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 24, 19);
INSERT INTO recenzija (sadrzaj, ocjena, trenutak_stvaranja, trenutak_promjene, sif_osoba, sif_servis) VALUES ('Semper risus in hendrerit gravida rutrum.', 1, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 26, 19);
INSERT INTO recenzija (sadrzaj, ocjena, trenutak_stvaranja, trenutak_promjene, sif_osoba, sif_servis) VALUES ('Urna et pharetra pharetra massa massa ultricies. Odio ut sem nulla pharetra diam sit amet.', 2, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 21, 20);
INSERT INTO recenzija (sadrzaj, ocjena, trenutak_stvaranja, trenutak_promjene, sif_osoba, sif_servis) VALUES ('Semper risus in hendrerit gravida rutrum.', 5, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 3, 20);
INSERT INTO recenzija (sadrzaj, ocjena, trenutak_stvaranja, trenutak_promjene, sif_osoba, sif_servis) VALUES ('Faucibus in ornare quam viverra orci sagittis eu volutpat.', 2, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 17, 20);
INSERT INTO recenzija (sadrzaj, ocjena, trenutak_stvaranja, trenutak_promjene, sif_osoba, sif_servis) VALUES ('Sit amet dictum sit amet justo donec enim diam vulputate.', 4, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 2, 20);
INSERT INTO recenzija (sadrzaj, ocjena, trenutak_stvaranja, trenutak_promjene, sif_osoba, sif_servis) VALUES ('Faucibus scelerisque eleifend donec pretium vulputate sapien nec.', 2, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 1, 21);
INSERT INTO recenzija (sadrzaj, ocjena, trenutak_stvaranja, trenutak_promjene, sif_osoba, sif_servis) VALUES ('Venenatis a condimentum vitae sapien. Quisque egestas diam in arcu cursus.', 2, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 2, 22);
INSERT INTO recenzija (sadrzaj, ocjena, trenutak_stvaranja, trenutak_promjene, sif_osoba, sif_servis) VALUES ('Lorem ipsum is placeholder text commonly used in the graphic, print, and publishing industries for previewing layouts and visual mockups.', 1, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 15, 22);
INSERT INTO recenzija (sadrzaj, ocjena, trenutak_stvaranja, trenutak_promjene, sif_osoba, sif_servis) VALUES ('Volutpat consequat mauris nunc congue nisi vitae.', 3, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 8, 23);
INSERT INTO recenzija (sadrzaj, ocjena, trenutak_stvaranja, trenutak_promjene, sif_osoba, sif_servis) VALUES ('Pretium lectus quam id leo in vitae turpis massa.', 3, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 28, 24);
INSERT INTO recenzija (sadrzaj, ocjena, trenutak_stvaranja, trenutak_promjene, sif_osoba, sif_servis) VALUES ('Faucibus scelerisque eleifend donec pretium vulputate sapien nec.', 1, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 10, 24);
INSERT INTO recenzija (sadrzaj, ocjena, trenutak_stvaranja, trenutak_promjene, sif_osoba, sif_servis) VALUES ('Lorem ipsum is placeholder text commonly used in the graphic, print, and publishing industries for previewing layouts and visual mockups.', 5, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 25, 25);
INSERT INTO recenzija (sadrzaj, ocjena, trenutak_stvaranja, trenutak_promjene, sif_osoba, sif_servis) VALUES ('Volutpat ac tincidunt vitae semper.', 3, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 15, 25);
INSERT INTO recenzija (sadrzaj, ocjena, trenutak_stvaranja, trenutak_promjene, sif_osoba, sif_servis) VALUES ('Faucibus scelerisque eleifend donec pretium vulputate sapien nec.', 1, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 10, 25);
INSERT INTO recenzija (sadrzaj, ocjena, trenutak_stvaranja, trenutak_promjene, sif_osoba, sif_servis) VALUES ('Consectetur adipiscing elit pellentesque habitant.', 3, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 20, 26);
INSERT INTO recenzija (sadrzaj, ocjena, trenutak_stvaranja, trenutak_promjene, sif_osoba, sif_servis) VALUES ('Pretium lectus quam id leo in vitae turpis massa.', 4, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 9, 27);
INSERT INTO recenzija (sadrzaj, ocjena, trenutak_stvaranja, trenutak_promjene, sif_osoba, sif_servis) VALUES ('Volutpat consequat mauris nunc congue nisi vitae.', 4, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 13, 27);
INSERT INTO recenzija (sadrzaj, ocjena, trenutak_stvaranja, trenutak_promjene, sif_osoba, sif_servis) VALUES ('Faucibus in ornare quam viverra orci sagittis eu volutpat.', 2, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 21, 27);
INSERT INTO recenzija (sadrzaj, ocjena, trenutak_stvaranja, trenutak_promjene, sif_osoba, sif_servis) VALUES ('Faucibus scelerisque eleifend donec pretium vulputate sapien nec.', 1, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 22, 27);
INSERT INTO recenzija (sadrzaj, ocjena, trenutak_stvaranja, trenutak_promjene, sif_osoba, sif_servis) VALUES ('Lorem ipsum is placeholder text commonly used in the graphic, print, and publishing industries for previewing layouts and visual mockups.', 1, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 12, 28);
INSERT INTO recenzija (sadrzaj, ocjena, trenutak_stvaranja, trenutak_promjene, sif_osoba, sif_servis) VALUES ('Semper risus in hendrerit gravida rutrum.', 4, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 30, 29);
INSERT INTO recenzija (sadrzaj, ocjena, trenutak_stvaranja, trenutak_promjene, sif_osoba, sif_servis) VALUES ('Semper risus in hendrerit gravida rutrum.', 4, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 5, 29);
INSERT INTO recenzija (sadrzaj, ocjena, trenutak_stvaranja, trenutak_promjene, sif_osoba, sif_servis) VALUES ('Venenatis a condimentum vitae sapien. Quisque egestas diam in arcu cursus.', 3, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 7, 30);
INSERT INTO recenzija (sadrzaj, ocjena, trenutak_stvaranja, trenutak_promjene, sif_osoba, sif_servis) VALUES ('Consectetur adipiscing elit pellentesque habitant.', 3, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 2, 30);
INSERT INTO recenzija (sadrzaj, ocjena, trenutak_stvaranja, trenutak_promjene, sif_osoba, sif_servis) VALUES ('Urna et pharetra pharetra massa massa ultricies. Odio ut sem nulla pharetra diam sit amet.', 4, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 20, 30);

/* Oglasi */
INSERT INTO oglas (naslov, opis, trenutak_stvaranja, trenutak_promjene, sif_status, sif_osoba, sif_kategorija_kvara, sif_mjesto) VALUES ('Urna et pharetra', 'Leo duis ut diam quam nulla porttitor massa id neque. Consectetur lorem donec massa sapien faucibus et molestie ac feugiat.', NOW()::TIMESTAMP, NOW()::TIMESTAMP, 2, 4, 18, 533);
INSERT INTO oglas (naslov, opis, trenutak_stvaranja, trenutak_promjene, sif_status, sif_osoba, sif_kategorija_kvara, sif_mjesto) VALUES ('Venenatis a condimentum vitae sapien', 'Venenatis a condimentum vitae sapien. Quisque egestas diam in arcu cursus.', NOW()::TIMESTAMP, NOW()::TIMESTAMP, 1, 4, 13, 686);
INSERT INTO oglas (naslov, opis, trenutak_stvaranja, trenutak_promjene, sif_status, sif_osoba, sif_kategorija_kvara, sif_mjesto) VALUES ('Semper risus', 'Urna et pharetra pharetra massa massa ultricies. Odio ut sem nulla pharetra diam sit amet.', NOW()::TIMESTAMP, NOW()::TIMESTAMP, 1, 4, 32, 512);
INSERT INTO oglas (naslov, opis, trenutak_stvaranja, trenutak_promjene, sif_status, sif_osoba, sif_kategorija_kvara, sif_mjesto) VALUES ('Faucibus in ornare', 'Semper risus in hendrerit gravida rutrum.', NOW()::TIMESTAMP, NOW()::TIMESTAMP, 1, 6, 33, 396);
INSERT INTO oglas (naslov, opis, trenutak_stvaranja, trenutak_promjene, sif_status, sif_osoba, sif_kategorija_kvara, sif_mjesto) VALUES ('Venenatis a condimentum vitae sapien', 'Lorem ipsum is placeholder text commonly used in the graphic, print, and publishing industries for previewing layouts and visual mockups.', NOW()::TIMESTAMP, NOW()::TIMESTAMP, 1, 6, 17, 446);
INSERT INTO oglas (naslov, opis, trenutak_stvaranja, trenutak_promjene, sif_status, sif_osoba, sif_kategorija_kvara, sif_mjesto) VALUES ('Pretium lectus', 'Semper risus in hendrerit gravida rutrum.', NOW()::TIMESTAMP, NOW()::TIMESTAMP, 1, 9, 32, 313);
INSERT INTO oglas (naslov, opis, trenutak_stvaranja, trenutak_promjene, sif_status, sif_osoba, sif_kategorija_kvara, sif_mjesto) VALUES ('Pretium lectus', 'Faucibus scelerisque eleifend donec pretium vulputate sapien nec.', NOW()::TIMESTAMP, NOW()::TIMESTAMP, 1, 9, 35, 96);
INSERT INTO oglas (naslov, opis, trenutak_stvaranja, trenutak_promjene, sif_status, sif_osoba, sif_kategorija_kvara, sif_mjesto) VALUES ('Pretium lectus', 'Consectetur adipiscing elit pellentesque habitant.', NOW()::TIMESTAMP, NOW()::TIMESTAMP, 1, 11, 25, 435);
INSERT INTO oglas (naslov, opis, trenutak_stvaranja, trenutak_promjene, sif_status, sif_osoba, sif_kategorija_kvara, sif_mjesto) VALUES ('Faucibus in ornare', 'Sit amet dictum sit amet justo donec enim diam vulputate.', NOW()::TIMESTAMP, NOW()::TIMESTAMP, 1, 11, 21, 724);
INSERT INTO oglas (naslov, opis, trenutak_stvaranja, trenutak_promjene, sif_status, sif_osoba, sif_kategorija_kvara, sif_mjesto) VALUES ('Odio ut sem', 'Sit amet dictum sit amet justo donec enim diam vulputate.', NOW()::TIMESTAMP, NOW()::TIMESTAMP, 2, 14, 42, 501);
INSERT INTO oglas (naslov, opis, trenutak_stvaranja, trenutak_promjene, sif_status, sif_osoba, sif_kategorija_kvara, sif_mjesto) VALUES ('Faucibus in ornare', 'Volutpat consequat mauris nunc congue nisi vitae.', NOW()::TIMESTAMP, NOW()::TIMESTAMP, 1, 15, 10, 408);
INSERT INTO oglas (naslov, opis, trenutak_stvaranja, trenutak_promjene, sif_status, sif_osoba, sif_kategorija_kvara, sif_mjesto) VALUES ('Pretium lectus', 'Semper risus in hendrerit gravida rutrum.', NOW()::TIMESTAMP, NOW()::TIMESTAMP, 1, 15, 11, 83);
INSERT INTO oglas (naslov, opis, trenutak_stvaranja, trenutak_promjene, sif_status, sif_osoba, sif_kategorija_kvara, sif_mjesto) VALUES ('Consectetur adipiscing', 'Volutpat ac tincidunt vitae semper.', NOW()::TIMESTAMP, NOW()::TIMESTAMP, 1, 15, 24, 572);
INSERT INTO oglas (naslov, opis, trenutak_stvaranja, trenutak_promjene, sif_status, sif_osoba, sif_kategorija_kvara, sif_mjesto) VALUES ('Quisque egestas diam in arcu cursus.', 'Pretium lectus quam id leo in vitae turpis massa.', NOW()::TIMESTAMP, NOW()::TIMESTAMP, 1, 16, 43, 805);
INSERT INTO oglas (naslov, opis, trenutak_stvaranja, trenutak_promjene, sif_status, sif_osoba, sif_kategorija_kvara, sif_mjesto) VALUES ('Odio ut sem nulla pharetra', 'Faucibus in ornare quam viverra orci sagittis eu volutpat.', NOW()::TIMESTAMP, NOW()::TIMESTAMP, 1, 17, 10, 488);
INSERT INTO oglas (naslov, opis, trenutak_stvaranja, trenutak_promjene, sif_status, sif_osoba, sif_kategorija_kvara, sif_mjesto) VALUES ('Odio ut sem nulla pharetra', 'Faucibus in ornare quam viverra orci sagittis eu volutpat.', NOW()::TIMESTAMP, NOW()::TIMESTAMP, 1, 17, 25, 585);
INSERT INTO oglas (naslov, opis, trenutak_stvaranja, trenutak_promjene, sif_status, sif_osoba, sif_kategorija_kvara, sif_mjesto) VALUES ('Odio ut sem', 'Venenatis a condimentum vitae sapien. Quisque egestas diam in arcu cursus.', NOW()::TIMESTAMP, NOW()::TIMESTAMP, 1, 17, 7, 552);
INSERT INTO oglas (naslov, opis, trenutak_stvaranja, trenutak_promjene, sif_status, sif_osoba, sif_kategorija_kvara, sif_mjesto) VALUES ('amet dictum sit amet', 'Pretium lectus quam id leo in vitae turpis massa.', NOW()::TIMESTAMP, NOW()::TIMESTAMP, 1, 18, 40, 118);
INSERT INTO oglas (naslov, opis, trenutak_stvaranja, trenutak_promjene, sif_status, sif_osoba, sif_kategorija_kvara, sif_mjesto) VALUES ('Urna et pharetra', 'Semper risus in hendrerit gravida rutrum.', NOW()::TIMESTAMP, NOW()::TIMESTAMP, 1, 20, 33, 824);
INSERT INTO oglas (naslov, opis, trenutak_stvaranja, trenutak_promjene, sif_status, sif_osoba, sif_kategorija_kvara, sif_mjesto) VALUES ('Faucibus in ornare', 'Venenatis a condimentum vitae sapien. Quisque egestas diam in arcu cursus.', NOW()::TIMESTAMP, NOW()::TIMESTAMP, 1, 20, 11, 118);
INSERT INTO oglas (naslov, opis, trenutak_stvaranja, trenutak_promjene, sif_status, sif_osoba, sif_kategorija_kvara, sif_mjesto) VALUES ('Consectetur lorem donec massa', 'Volutpat ac tincidunt vitae semper.', NOW()::TIMESTAMP, NOW()::TIMESTAMP, 1, 20, 37, 287);
INSERT INTO oglas (naslov, opis, trenutak_stvaranja, trenutak_promjene, sif_status, sif_osoba, sif_kategorija_kvara, sif_mjesto) VALUES ('Quisque egestas diam in arcu cursus.', 'Faucibus in ornare quam viverra orci sagittis eu volutpat.', NOW()::TIMESTAMP, NOW()::TIMESTAMP, 1, 20, 46, 171);
INSERT INTO oglas (naslov, opis, trenutak_stvaranja, trenutak_promjene, sif_status, sif_osoba, sif_kategorija_kvara, sif_mjesto) VALUES ('Consectetur adipiscing', 'Faucibus scelerisque eleifend donec pretium vulputate sapien nec.', NOW()::TIMESTAMP, NOW()::TIMESTAMP, 1, 22, 11, 388);
INSERT INTO oglas (naslov, opis, trenutak_stvaranja, trenutak_promjene, sif_status, sif_osoba, sif_kategorija_kvara, sif_mjesto) VALUES ('Consectetur adipiscing', 'Leo duis ut diam quam nulla porttitor massa id neque. Consectetur lorem donec massa sapien faucibus et molestie ac feugiat.', NOW()::TIMESTAMP, NOW()::TIMESTAMP, 1, 22, 14, 600);
INSERT INTO oglas (naslov, opis, trenutak_stvaranja, trenutak_promjene, sif_status, sif_osoba, sif_kategorija_kvara, sif_mjesto) VALUES ('Odio ut sem nulla pharetra', 'Venenatis a condimentum vitae sapien. Quisque egestas diam in arcu cursus.', NOW()::TIMESTAMP, NOW()::TIMESTAMP, 1, 22, 42, 759);
INSERT INTO oglas (naslov, opis, trenutak_stvaranja, trenutak_promjene, sif_status, sif_osoba, sif_kategorija_kvara, sif_mjesto) VALUES ('Odio ut sem', 'Lorem ipsum is placeholder text commonly used in the graphic, print, and publishing industries for previewing layouts and visual mockups.', NOW()::TIMESTAMP, NOW()::TIMESTAMP, 1, 22, 14, 958);
INSERT INTO oglas (naslov, opis, trenutak_stvaranja, trenutak_promjene, sif_status, sif_osoba, sif_kategorija_kvara, sif_mjesto) VALUES ('Semper risus', 'Faucibus scelerisque eleifend donec pretium vulputate sapien nec.', NOW()::TIMESTAMP, NOW()::TIMESTAMP, 1, 23, 33, 90);
INSERT INTO oglas (naslov, opis, trenutak_stvaranja, trenutak_promjene, sif_status, sif_osoba, sif_kategorija_kvara, sif_mjesto) VALUES ('amet dictum sit amet', 'Faucibus in ornare quam viverra orci sagittis eu volutpat.', NOW()::TIMESTAMP, NOW()::TIMESTAMP, 1, 23, 33, 312);
INSERT INTO oglas (naslov, opis, trenutak_stvaranja, trenutak_promjene, sif_status, sif_osoba, sif_kategorija_kvara, sif_mjesto) VALUES ('Urna et pharetra', 'Leo duis ut diam quam nulla porttitor massa id neque. Consectetur lorem donec massa sapien faucibus et molestie ac feugiat.', NOW()::TIMESTAMP, NOW()::TIMESTAMP, 1, 23, 36, 74);
INSERT INTO oglas (naslov, opis, trenutak_stvaranja, trenutak_promjene, sif_status, sif_osoba, sif_kategorija_kvara, sif_mjesto) VALUES ('Consectetur adipiscing', 'Semper risus in hendrerit gravida rutrum.', NOW()::TIMESTAMP, NOW()::TIMESTAMP, 2, 25, 44, 98);
INSERT INTO oglas (naslov, opis, trenutak_stvaranja, trenutak_promjene, sif_status, sif_osoba, sif_kategorija_kvara, sif_mjesto) VALUES ('Quisque egestas diam in arcu cursus.', 'Leo duis ut diam quam nulla porttitor massa id neque. Consectetur lorem donec massa sapien faucibus et molestie ac feugiat.', NOW()::TIMESTAMP, NOW()::TIMESTAMP, 1, 25, 40, 174);
INSERT INTO oglas (naslov, opis, trenutak_stvaranja, trenutak_promjene, sif_status, sif_osoba, sif_kategorija_kvara, sif_mjesto) VALUES ('Quisque egestas diam in arcu cursus.', 'Faucibus in ornare quam viverra orci sagittis eu volutpat.', NOW()::TIMESTAMP, NOW()::TIMESTAMP, 2, 25, 14, 879);

/* Slike za oglase */
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-fauxels-3184454', 'nhiwgu19vxyuwn3psuls', 'https://res.cloudinary.com/eservis/image/upload/v1620246823/nhiwgu19vxyuwn3psuls.jpg', 1);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-josh-sorenson-1714208', 'exypyfawi41arc3cmxak', 'https://res.cloudinary.com/eservis/image/upload/v1620246837/exypyfawi41arc3cmxak.jpg', 2);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-designecologist-1779487', 'elmn31vgcki3rlqd2lad', 'https://res.cloudinary.com/eservis/image/upload/v1620246843/elmn31vgcki3rlqd2lad.jpg', 3);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-stas-knop-1298601', 'edaxfzmn6jfk18lt84y0', 'https://res.cloudinary.com/eservis/image/upload/v1620246850/edaxfzmn6jfk18lt84y0.jpg', 4);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-stas-knop-2520829', 'ykyemudow4gmqmumfyp6', 'https://res.cloudinary.com/eservis/image/upload/v1620246856/ykyemudow4gmqmumfyp6.jpg', 5);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-cleyder-duque-3637728', 'krju0b54edk9z2dr4wbz', 'https://res.cloudinary.com/eservis/image/upload/v1620246869/krju0b54edk9z2dr4wbz.jpg', 6);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-curtis-adams-3935334', 'hg6jrv1jcu1qkij3nf7k', 'https://res.cloudinary.com/eservis/image/upload/v1620246875/hg6jrv1jcu1qkij3nf7k.jpg', 7);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-adrienne-andersen-2254065', 'tt7fbz2tz0slajrqizzi', 'https://res.cloudinary.com/eservis/image/upload/v1620246883/tt7fbz2tz0slajrqizzi.jpg', 8);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-free-creative-stuff-1476321', 'j4ctct5nqzxbvcplq5hc', 'https://res.cloudinary.com/eservis/image/upload/v1620246891/j4ctct5nqzxbvcplq5hc.jpg', 9);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-skitterphoto-1388947', 'dprn65sb7x8zxksqk2f1', 'https://res.cloudinary.com/eservis/image/upload/v1620246896/dprn65sb7x8zxksqk2f1.jpg', 10);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-energepiccom-288479', 'yq4f8ikuprk8hqe2qpxi', 'https://res.cloudinary.com/eservis/image/upload/v1620246901/yq4f8ikuprk8hqe2qpxi.jpg', 11);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-fauxels-3184454', 'pzznexgopr62qm9crhe8', 'https://res.cloudinary.com/eservis/image/upload/v1620246909/pzznexgopr62qm9crhe8.jpg', 12);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-josh-sorenson-1714208', 'm7ntqndgt0morivd7jlf', 'https://res.cloudinary.com/eservis/image/upload/v1620246916/m7ntqndgt0morivd7jlf.jpg', 13);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-designecologist-1779487', 'ada1pcu6w0kwcshtczcm', 'https://res.cloudinary.com/eservis/image/upload/v1620246921/ada1pcu6w0kwcshtczcm.jpg', 14);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-stas-knop-1298601', 'jqwj2ra3d4g1dkfyjjqi', 'https://res.cloudinary.com/eservis/image/upload/v1620246928/jqwj2ra3d4g1dkfyjjqi.jpg', 15);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-stas-knop-2520829', 'udygb43jtqneqld252qi', 'https://res.cloudinary.com/eservis/image/upload/v1620246934/udygb43jtqneqld252qi.jpg', 16);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-cleyder-duque-3637728', 'xxdi8dts9njxvdfruhnn', 'https://res.cloudinary.com/eservis/image/upload/v1620246941/xxdi8dts9njxvdfruhnn.jpg', 17);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-curtis-adams-3935334', 'qd1bk0apmrhlpb1hi46j', 'https://res.cloudinary.com/eservis/image/upload/v1620246948/qd1bk0apmrhlpb1hi46j.jpg', 18);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-adrienne-andersen-2254065', 'xuh0oswhhxn7e1gqsz3z', 'https://res.cloudinary.com/eservis/image/upload/v1620246956/xuh0oswhhxn7e1gqsz3z.jpg', 19);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-free-creative-stuff-1476321', 'fojqeaqyga7yxemg2j0d', 'https://res.cloudinary.com/eservis/image/upload/v1620246962/fojqeaqyga7yxemg2j0d.jpg', 20);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-skitterphoto-1388947', 'tjggwzbovslmpx88zmgk', 'https://res.cloudinary.com/eservis/image/upload/v1620246970/tjggwzbovslmpx88zmgk.jpg', 21);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-energepiccom-288479', 'vidzkwz93mrhuleyc79m', 'https://res.cloudinary.com/eservis/image/upload/v1620246974/vidzkwz93mrhuleyc79m.jpg', 22);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-fauxels-3184454', 'iqmccnmifdqsiukl9vhg', 'https://res.cloudinary.com/eservis/image/upload/v1620246982/iqmccnmifdqsiukl9vhg.jpg', 23);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-josh-sorenson-1714208', 'ywcqyxbod7jqyypnkams', 'https://res.cloudinary.com/eservis/image/upload/v1620246990/ywcqyxbod7jqyypnkams.jpg', 24);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-designecologist-1779487', 'jth7feqbhce3mju2krxz', 'https://res.cloudinary.com/eservis/image/upload/v1620246996/jth7feqbhce3mju2krxz.jpg', 25);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-stas-knop-1298601', 'jtyvyul3u9kzjqywhgql', 'https://res.cloudinary.com/eservis/image/upload/v1620247003/jtyvyul3u9kzjqywhgql.jpg', 26);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-stas-knop-2520829', 'kfwyttxpkjwsmzaejnz3', 'https://res.cloudinary.com/eservis/image/upload/v1620247010/kfwyttxpkjwsmzaejnz3.jpg', 27);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-cleyder-duque-3637728', 'gpou39we5xnavwgsz35n', 'https://res.cloudinary.com/eservis/image/upload/v1620247018/gpou39we5xnavwgsz35n.jpg', 28);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-curtis-adams-3935334', 'fcl9ytdqdiseg8nm2be9', 'https://res.cloudinary.com/eservis/image/upload/v1620247025/fcl9ytdqdiseg8nm2be9.jpg', 29);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-adrienne-andersen-2254065', 'd5l3fz9kz8fjzpmxt2vs', 'https://res.cloudinary.com/eservis/image/upload/v1620247033/d5l3fz9kz8fjzpmxt2vs.jpg', 30);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-free-creative-stuff-1476321', 'doxfctteno3vmormpzwh', 'https://res.cloudinary.com/eservis/image/upload/v1620247040/doxfctteno3vmormpzwh.jpg', 31);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-skitterphoto-1388947', 'nhqdjj5hixlypbw9wydb', 'https://res.cloudinary.com/eservis/image/upload/v1620247045/nhqdjj5hixlypbw9wydb.jpg', 1);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-energepiccom-288479', 'djzhaxejtbpiqkzj2vao', 'https://res.cloudinary.com/eservis/image/upload/v1620247050/djzhaxejtbpiqkzj2vao.jpg', 2);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-fauxels-3184454', 'smbknbupxbbbl5devklb', 'https://res.cloudinary.com/eservis/image/upload/v1620247060/smbknbupxbbbl5devklb.jpg', 3);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-josh-sorenson-1714208', 'a104hmlapvhdwcrbylgr', 'https://res.cloudinary.com/eservis/image/upload/v1620247067/a104hmlapvhdwcrbylgr.jpg', 4);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-designecologist-1779487', 'oyz1ce9c5uhh5rcrsyko', 'https://res.cloudinary.com/eservis/image/upload/v1620247121/oyz1ce9c5uhh5rcrsyko.jpg', 5);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-stas-knop-1298601', 'kuky6ybbuzgflqsdtt4z', 'https://res.cloudinary.com/eservis/image/upload/v1620247140/kuky6ybbuzgflqsdtt4z.jpg', 6);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-stas-knop-2520829', 'jsfwnscpmxl72gxi8ct9', 'https://res.cloudinary.com/eservis/image/upload/v1620247147/jsfwnscpmxl72gxi8ct9.jpg', 7);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-cleyder-duque-3637728', 'e3hqbgzlgrwd1amowcxe', 'https://res.cloudinary.com/eservis/image/upload/v1620247155/e3hqbgzlgrwd1amowcxe.jpg', 8);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-curtis-adams-3935334', 'a7qyzfndwyl03fvwlop2', 'https://res.cloudinary.com/eservis/image/upload/v1620247162/a7qyzfndwyl03fvwlop2.jpg', 9);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-adrienne-andersen-2254065', 'ptzwumldxaxarf4yxbzu', 'https://res.cloudinary.com/eservis/image/upload/v1620247169/ptzwumldxaxarf4yxbzu.jpg', 10);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-free-creative-stuff-1476321', 'lx7p3gx0c4ltn5x6mblf', 'https://res.cloudinary.com/eservis/image/upload/v1620247175/lx7p3gx0c4ltn5x6mblf.jpg', 11);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-skitterphoto-1388947', 'd071e9lrdh1gfpvotnue', 'https://res.cloudinary.com/eservis/image/upload/v1620247180/d071e9lrdh1gfpvotnue.jpg', 12);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-energepiccom-288479', 'q0tsiu8d5kojqpc3eiq3', 'https://res.cloudinary.com/eservis/image/upload/v1620247185/q0tsiu8d5kojqpc3eiq3.jpg', 13);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-fauxels-3184454', 'hlrxqrvkqnd7vt435knw', 'https://res.cloudinary.com/eservis/image/upload/v1620247215/hlrxqrvkqnd7vt435knw.jpg', 14);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-josh-sorenson-1714208', 'dgxmwjytd7ck0motsiue', 'https://res.cloudinary.com/eservis/image/upload/v1620247222/dgxmwjytd7ck0motsiue.jpg', 15);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-designecologist-1779487', 'vtk0e4izwpgyzqx6ol7b', 'https://res.cloudinary.com/eservis/image/upload/v1620247227/vtk0e4izwpgyzqx6ol7b.jpg', 16);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-stas-knop-1298601', 'y4lomhktpqx7cw2ydy7v', 'https://res.cloudinary.com/eservis/image/upload/v1620247234/y4lomhktpqx7cw2ydy7v.jpg', 17);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-stas-knop-2520829', 'rguyv8s0j6mfjlrq6pc9', 'https://res.cloudinary.com/eservis/image/upload/v1620247240/rguyv8s0j6mfjlrq6pc9.jpg', 18);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-cleyder-duque-3637728', 'wfotf4k88hcpkpim2xiq', 'https://res.cloudinary.com/eservis/image/upload/v1620247248/wfotf4k88hcpkpim2xiq.jpg', 19);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-curtis-adams-3935334', 'upblz8gkfx34h9rxedql', 'https://res.cloudinary.com/eservis/image/upload/v1620247254/upblz8gkfx34h9rxedql.jpg', 20);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-adrienne-andersen-2254065', 'o9tvp747bxgwsmtriu1b', 'https://res.cloudinary.com/eservis/image/upload/v1620247261/o9tvp747bxgwsmtriu1b.jpg', 21);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-free-creative-stuff-1476321', 'jucvhfhyjwmwwgftpgrd', 'https://res.cloudinary.com/eservis/image/upload/v1620247267/jucvhfhyjwmwwgftpgrd.jpg', 22);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-skitterphoto-1388947', 'mbmrzsxvdwaqxku2vzjc', 'https://res.cloudinary.com/eservis/image/upload/v1620247272/mbmrzsxvdwaqxku2vzjc.jpg', 23);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-energepiccom-288479', 'oxpzb0ymkto1z2pwyari', 'https://res.cloudinary.com/eservis/image/upload/v1620247277/oxpzb0ymkto1z2pwyari.jpg', 24);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-fauxels-3184454', 'owd7usd7nomjiu2rztlr', 'https://res.cloudinary.com/eservis/image/upload/v1620247289/owd7usd7nomjiu2rztlr.jpg', 25);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-josh-sorenson-1714208', 'tom202iiqfhobnady5ul', 'https://res.cloudinary.com/eservis/image/upload/v1620247296/tom202iiqfhobnady5ul.jpg', 26);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-designecologist-1779487', 'ky6oqrbidagfj9j0alw9', 'https://res.cloudinary.com/eservis/image/upload/v1620247301/ky6oqrbidagfj9j0alw9.jpg', 27);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-stas-knop-1298601', 'ntjvixjaamz83aniteau', 'https://res.cloudinary.com/eservis/image/upload/v1620247307/ntjvixjaamz83aniteau.jpg', 28);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-stas-knop-2520829', 'ffmmd05aqptjadqamk0n', 'https://res.cloudinary.com/eservis/image/upload/v1620247313/ffmmd05aqptjadqamk0n.jpg', 29);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-cleyder-duque-3637728', 'uufq1djjleftxfb946a8', 'https://res.cloudinary.com/eservis/image/upload/v1620247322/uufq1djjleftxfb946a8.jpg', 30);
INSERT INTO slika (naziv_slika, cloudinary_id, url, sif_oglas) VALUES ('pexels-curtis-adams-3935334', 'i5xjojic7pkv0f7zysog', 'https://res.cloudinary.com/eservis/image/upload/v1620247328/i5xjojic7pkv0f7zysog.jpg', 31);

/* Ponude */
INSERT INTO ponuda (naslov, opis, cijena, sif_servis, trenutak_stvaranja, trenutak_promjene, sif_status, sif_oglas) VALUES ('Quisque egestas diam in arcu cursus.', 'Faucibus scelerisque eleifend donec pretium vulputate sapien nec.', 72, 2, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 3, 23);
INSERT INTO ponuda (naslov, opis, cijena, sif_servis, trenutak_stvaranja, trenutak_promjene, sif_status, sif_oglas) VALUES ('risus in hendrerit', 'Volutpat consequat mauris nunc congue nisi vitae.', 141, 2, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 1, 5);
INSERT INTO ponuda (naslov, opis, cijena, sif_servis, trenutak_stvaranja, trenutak_promjene, sif_status, sif_oglas) VALUES ('Odio ut sem', 'Venenatis a condimentum vitae sapien. Quisque egestas diam in arcu cursus.', 683, 2, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 2, 20);
INSERT INTO ponuda (naslov, opis, cijena, sif_servis, trenutak_stvaranja, trenutak_promjene, sif_status, sif_oglas) VALUES ('Consectetur lorem donec massa', 'Venenatis a condimentum vitae sapien. Quisque egestas diam in arcu cursus.', 746, 4, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 2, 11);
INSERT INTO ponuda (naslov, opis, cijena, sif_servis, trenutak_stvaranja, trenutak_promjene, sif_status, sif_oglas) VALUES ('risus in hendrerit', 'Faucibus in ornare quam viverra orci sagittis eu volutpat.', 302, 6, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 3, 13);
INSERT INTO ponuda (naslov, opis, cijena, sif_servis, trenutak_stvaranja, trenutak_promjene, sif_status, sif_oglas) VALUES ('Odio ut sem', 'Leo duis ut diam quam nulla porttitor massa id neque. Consectetur lorem donec massa sapien faucibus et molestie ac feugiat.', 556, 6, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 1, 22);
INSERT INTO ponuda (naslov, opis, cijena, sif_servis, trenutak_stvaranja, trenutak_promjene, sif_status, sif_oglas) VALUES ('Odio ut sem', 'Pretium lectus quam id leo in vitae turpis massa.', 420, 7, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 3, 18);
INSERT INTO ponuda (naslov, opis, cijena, sif_servis, trenutak_stvaranja, trenutak_promjene, sif_status, sif_oglas) VALUES ('Semper risus', 'Faucibus scelerisque eleifend donec pretium vulputate sapien nec.', 574, 7, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 3, 21);
INSERT INTO ponuda (naslov, opis, cijena, sif_servis, trenutak_stvaranja, trenutak_promjene, sif_status, sif_oglas) VALUES ('Faucibus in ornare', 'Consectetur adipiscing elit pellentesque habitant.', 729, 7, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 3, 4);
INSERT INTO ponuda (naslov, opis, cijena, sif_servis, trenutak_stvaranja, trenutak_promjene, sif_status, sif_oglas) VALUES ('Urna et pharetra', 'Faucibus scelerisque eleifend donec pretium vulputate sapien nec.', 893, 9, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 3, 4);
INSERT INTO ponuda (naslov, opis, cijena, sif_servis, trenutak_stvaranja, trenutak_promjene, sif_status, sif_oglas) VALUES ('Faucibus in ornare', 'Leo duis ut diam quam nulla porttitor massa id neque. Consectetur lorem donec massa sapien faucibus et molestie ac feugiat.', 558, 9, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 1, 1);
INSERT INTO ponuda (naslov, opis, cijena, sif_servis, trenutak_stvaranja, trenutak_promjene, sif_status, sif_oglas) VALUES ('Consectetur lorem donec massa', 'Leo duis ut diam quam nulla porttitor massa id neque. Consectetur lorem donec massa sapien faucibus et molestie ac feugiat.', 359, 10, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 1, 22);
INSERT INTO ponuda (naslov, opis, cijena, sif_servis, trenutak_stvaranja, trenutak_promjene, sif_status, sif_oglas) VALUES ('Pretium lectus', 'Lorem ipsum is placeholder text commonly used in the graphic, print, and publishing industries for previewing layouts and visual mockups.', 158, 10, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 3, 20);
INSERT INTO ponuda (naslov, opis, cijena, sif_servis, trenutak_stvaranja, trenutak_promjene, sif_status, sif_oglas) VALUES ('Semper risus', 'Volutpat ac tincidunt vitae semper.', 748, 10, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 1, 12);
INSERT INTO ponuda (naslov, opis, cijena, sif_servis, trenutak_stvaranja, trenutak_promjene, sif_status, sif_oglas) VALUES ('amet dictum sit amet', 'Volutpat consequat mauris nunc congue nisi vitae.', 818, 13, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 3, 23);
INSERT INTO ponuda (naslov, opis, cijena, sif_servis, trenutak_stvaranja, trenutak_promjene, sif_status, sif_oglas) VALUES ('Consectetur adipiscing', 'Semper risus in hendrerit gravida rutrum.', 639, 13, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 3, 22);
INSERT INTO ponuda (naslov, opis, cijena, sif_servis, trenutak_stvaranja, trenutak_promjene, sif_status, sif_oglas) VALUES ('Pretium lectus', 'Pretium lectus quam id leo in vitae turpis massa.', 396, 13, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 1, 1);
INSERT INTO ponuda (naslov, opis, cijena, sif_servis, trenutak_stvaranja, trenutak_promjene, sif_status, sif_oglas) VALUES ('Faucibus in ornare', 'Faucibus scelerisque eleifend donec pretium vulputate sapien nec.', 672, 13, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 1, 15);
INSERT INTO ponuda (naslov, opis, cijena, sif_servis, trenutak_stvaranja, trenutak_promjene, sif_status, sif_oglas) VALUES ('Venenatis a condimentum vitae sapien', 'Pretium lectus quam id leo in vitae turpis massa.', 597, 18, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 3, 17);
INSERT INTO ponuda (naslov, opis, cijena, sif_servis, trenutak_stvaranja, trenutak_promjene, sif_status, sif_oglas) VALUES ('Odio ut sem nulla pharetra', 'Sit amet dictum sit amet justo donec enim diam vulputate.', 888, 19, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 1, 10);
INSERT INTO ponuda (naslov, opis, cijena, sif_servis, trenutak_stvaranja, trenutak_promjene, sif_status, sif_oglas) VALUES ('Consectetur lorem donec massa', 'Semper risus in hendrerit gravida rutrum.', 124, 19, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 1, 4);
INSERT INTO ponuda (naslov, opis, cijena, sif_servis, trenutak_stvaranja, trenutak_promjene, sif_status, sif_oglas) VALUES ('Odio ut sem', 'Venenatis a condimentum vitae sapien. Quisque egestas diam in arcu cursus.', 707, 20, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 1, 18);
INSERT INTO ponuda (naslov, opis, cijena, sif_servis, trenutak_stvaranja, trenutak_promjene, sif_status, sif_oglas) VALUES ('Consectetur adipiscing', 'Volutpat consequat mauris nunc congue nisi vitae.', 213, 20, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 1, 14);
INSERT INTO ponuda (naslov, opis, cijena, sif_servis, trenutak_stvaranja, trenutak_promjene, sif_status, sif_oglas) VALUES ('Semper risus', 'Faucibus scelerisque eleifend donec pretium vulputate sapien nec.', 376, 22, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 1, 25);
INSERT INTO ponuda (naslov, opis, cijena, sif_servis, trenutak_stvaranja, trenutak_promjene, sif_status, sif_oglas) VALUES ('Consectetur adipiscing', 'Semper risus in hendrerit gravida rutrum.', 409, 22, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 3, 11);
INSERT INTO ponuda (naslov, opis, cijena, sif_servis, trenutak_stvaranja, trenutak_promjene, sif_status, sif_oglas) VALUES ('Venenatis a condimentum vitae sapien', 'Lorem ipsum is placeholder text commonly used in the graphic, print, and publishing industries for previewing layouts and visual mockups.', 245, 23, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 2, 18);
INSERT INTO ponuda (naslov, opis, cijena, sif_servis, trenutak_stvaranja, trenutak_promjene, sif_status, sif_oglas) VALUES ('Venenatis a condimentum vitae sapien', 'Volutpat ac tincidunt vitae semper.', 506, 23, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 1, 19);
INSERT INTO ponuda (naslov, opis, cijena, sif_servis, trenutak_stvaranja, trenutak_promjene, sif_status, sif_oglas) VALUES ('Consectetur adipiscing', 'Venenatis a condimentum vitae sapien. Quisque egestas diam in arcu cursus.', 189, 23, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 1, 29);
INSERT INTO ponuda (naslov, opis, cijena, sif_servis, trenutak_stvaranja, trenutak_promjene, sif_status, sif_oglas) VALUES ('Consectetur adipiscing', 'Faucibus in ornare quam viverra orci sagittis eu volutpat.', 268, 24, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 3, 10);
INSERT INTO ponuda (naslov, opis, cijena, sif_servis, trenutak_stvaranja, trenutak_promjene, sif_status, sif_oglas) VALUES ('Faucibus in ornare', 'Sit amet dictum sit amet justo donec enim diam vulputate.', 578, 24, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 3, 25);
INSERT INTO ponuda (naslov, opis, cijena, sif_servis, trenutak_stvaranja, trenutak_promjene, sif_status, sif_oglas) VALUES ('Odio ut sem nulla pharetra', 'Venenatis a condimentum vitae sapien. Quisque egestas diam in arcu cursus.', 680, 24, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 3, 1);
INSERT INTO ponuda (naslov, opis, cijena, sif_servis, trenutak_stvaranja, trenutak_promjene, sif_status, sif_oglas) VALUES ('amet dictum sit amet', 'Leo duis ut diam quam nulla porttitor massa id neque. Consectetur lorem donec massa sapien faucibus et molestie ac feugiat.', 53, 27, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 1, 10);
INSERT INTO ponuda (naslov, opis, cijena, sif_servis, trenutak_stvaranja, trenutak_promjene, sif_status, sif_oglas) VALUES ('Urna et pharetra', 'Urna et pharetra pharetra massa massa ultricies. Odio ut sem nulla pharetra diam sit amet.', 260, 29, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 1, 6);
INSERT INTO ponuda (naslov, opis, cijena, sif_servis, trenutak_stvaranja, trenutak_promjene, sif_status, sif_oglas) VALUES ('Consectetur adipiscing', 'Consectetur adipiscing elit pellentesque habitant.', 424, 29, NOW()::TIMESTAMP, NOW()::TIMESTAMP, 1, 11);