export const REGISTER_LOADING = "REGISTER_LOADING";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_ERROR = "REGISTER_ERROR";
export const REGISTER_ERROR_REMOVE = "REGISTER_ERROR_REMOVE";
export const REGISTER_AFTER_REDIRECT = "REGISTER_AFTER_REDIRECT";

export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGIN_ERROR_REMOVE = "LOGIN_ERROR_REMOVE";

export const LOGOUT = "LOGOUT";

export const UPDATE_AUTH_DATA = "UPDATE_AUTH_DATA";

export const SET_SIDEBAR_SHOW = "SET_SIDEBAR_SHOW";

export const USER_DATA_LOADING = "USER_DATA_LOADING";
export const USER_DATA_SUCCESS = "USER_DATA_SUCCESS";
export const USER_DATA_ERROR = "USER_DATA_ERROR";

export const SERVICE_DATA_LOADING = "SERVICE_DATA_LOADING";
export const SERVICE_DATA_SUCCESS = "SERVICE_DATA_SUCCESS";
export const SERVICE_DATA_ERROR = "SERVICE_DATA_ERROR";

export const SERVICE_FAULT_LOADING = "SERVICE_FAULT_LOADING";
export const SERVICE_FAULT_SUCCESS = "SERVICE_FAULT_SUCCESS";
export const SERVICE_FAULT_ERROR = "SERVICE_FAULT_ERROR";

export const UPLOAD_PROFILE_PICTURE_LOADING = "UPLOAD_PROFILE_PICTURE_LOADING";
export const UPLOAD_PROFILE_PICTURE_SUCCESS = "UPLOAD_PROFILE_PICTURE_SUCCESS";
export const UPLOAD_PROFILE_PICTURE_ERROR = "UPLOAD_PROFILE_PICTURE_ERROR";

export const ADD_CONTACT = "ADD_CONTACT";

export const CREATE_CONVERSATION = "CREATE_CONVERSATION";
export const ADD_MESSAGE = "ADD_MESSAGE";