export const REGISTER_LOADING = "REGISTER_LOADING";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_ERROR = "REGISTER_ERROR";
export const REGISTER_ERROR_REMOVE = "REGISTER_ERROR_REMOVE";
export const REGISTER_AFTER_REDIRECT = "REGISTER_AFTER_REDIRECT";

export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGIN_ERROR_REMOVE = "LOGIN_ERROR_REMOVE";

export const LOGOUT = "LOGOUT";

export const SET_SIDEBAR_SHOW = "SET_SIDEBAR_SHOW";

export const USER_DATA_LOADING = "USER_DATA_LOADING";
export const USER_DATA_SUCCESS = "USER_DATA_SUCCESS";
export const USER_DATA_ERROR = "USER_DATA_ERROR";