export const SERVICE_DASHBOARD = "SERVICE_DASHBOARD";
export const SERVICE_MESSAGES = "SERVICE_MESSAGES";
export const SERVICE_PROFILE = "SERVICE_PROFILE";
export const SERVICE_OFFERS_ACTIVE = "SERVICE_OFFERS_ACTIVE";
export const SERVICE_OFFERS_HISTORY = "SERVICE_OFFERS_HISTORY";
export const SERVICE_SERVICERS = "SERVICE_SERVICERS";
export const SERVICE_SEARCH = "SERVICE_SEARCH";