export const USER_DASHBOARD = "USER_DASHBOARD";
export const USER_MESSAGES = "USER_MESSAGES";
export const USER_PROFILE = "USER_PROFILE";
export const USER_LISTINGS_ACTIVE = "USER_LISTINGS_ACTIVE";
export const USER_LISTINGS_HISTORY = "USER_LISTINGS_HISTORY";
export const USER_SERVICERS = "USER_SERVICERS";